### ISSUE TITLE
Provide third-party paper embeddings via the Semantic Scholar APIs

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#102]
**Is your feature request related to a problem? Please describe.**
Several researchers are working on improved embeddings, but don't have a scalable way to share the embeddings with potential users. There's evidence of high demand for paper embeddings in general ([e.g., see SPECTER citations](https://www.semanticscholar.org/paper/SPECTER%3A-Document-level-Representation-Learning-Cohan-Feldman/a3e4ceb42cbcd2c807d53aff90a8cb1f5ee3f031)).

**Describe the solution you'd like**
Provide researchers who are developing paper embeddings (e.g., Ken, Sheshera, Nihar, and the SciNCL) with a TIMO based self hosted service which they can modify to provide their own embeddings given a paper ID, then allow users of the Semantic Scholar APIs to get paper embeddings from any number of providers who register their services with our APIs. 

**Describe alternatives you've considered**
N/A

**Additional context**
Email thread

**Comment by cfiorelli** [comment]
Embeddings launched and ongoing iterations in progress.
