### ISSUE TITLE
Q: Which venue information are retrieved, if a paper has been accepted to a venue and at the same time published on arXiv

### ISSUE THREAD

**Issue by osmalpkoras** [allenai/s2-folks#115]
Q: Which venue information are retrieved, if a paper has been accepted to a venue and at the same time published on arXiv?

Background: We are doing a survey on NLP and reiled on the semantic scholar API to search for relevant papers. For our survey, we assumed that the API will (always) return a peer-reviewed venue, if the paper has been published on one, and return arXiv for the venue, if the paper had not been peer-reviewed and uploaded on arXiv only.

Does our assumption generally hold true? I know there can always be some bugs in the API or falsely classified papers, but for simplicity sake, I would like to assume the ideal case for this case.

We couldn't find an answer in the documentation, but this is an important issue to us (and probably others) and would appreciate if you could elaborate on it.

**Comment by cfiorelli** [comment]
@osmalpkoras 
Generally we expose the most recent paper which should always be the peer review.
Thanks for the question!
