### ISSUE TITLE
I want to get more than 10K papers using the search endpoint

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#12]
From [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/55933)
> I just wanna know how to resolve the limitation of the ?offset? and ?limit? in API. For example, I cannot get the whole papers about customer service in 2022 by using API, because "The sum of offset and limit must be < 10000" while the number of papers that I want EXCEEDS 10000. Please help me solve the problem, thank you so much.

**Comment by cyuyu1989** [comment]
I just can‘t solve this problem when I use the API from semantic scholar to find abundant papers.
![Uploading 469E91A1-22FD-4126-9F6E-4F1E11829B2B.png…]()

**Comment by Androbin** [comment]
@cyuyu1989 Can you tell us a little bit about your use case?

I would think that the 10001st search result for any given search query is rather unlikely to be a good match for that query.

**Comment by cyuyu1989** [comment]
@Androbin Thank you for your help. Actually,I
was making a research by using semantic scholar API. So the more papers I get, the better the research will be.I have already searched more results with filters such as year
.But the number of papers is still not enough. Therefore,I wanna know how to breakthrough the limitation in semantic scholar API.

**Comment by aletar89** [comment]
It looks like search is not quite the right endpoint for this. I would suggest using the bulk download and using as many papers as you want.
@wammar This seems to be a common (and bad) use case for the search API. Maybe a solution would be an API that returns paper ids based on filters without a search query? For example, I want all the computer science papers from 2022 with more than 0 citations and get the paper-ids of all the papers (paginated if needed), then I can run over the list and do further analysis with the paper-details API.

**Comment by wammar** [comment]
@aletar89 Thanks for sharing your thoughts on this. We're actively discussing how to enable use cases of this type but we haven't converged on a specific solution yet. I'm creating a new issue for the feature request you suggested.

**Comment by wammar** [comment]
@cyuyu1989 Would you mind providing more details on the research you're doing. How do you determine which papers are relevant to your research?

**Comment by csaparna** [comment]
> 

Is it possible to filter like this currently at the paper endpoint?

**Comment by csaparna** [comment]
> You might be able to get more papers by making multiple requests with different filters.
> 
> For example you could filter by "publicationTypes" and make one request for "Review", one request for "JournalArticle" and so on. You can do the same for "year" and "fieldsOfStudy".
> 
> The idea is that the search results for the same query but with different filters are guaranteed to be non-overlapping. So you can get more papers for the same query compared to the naive approach.

Is it possible to filter like this currently at the paper endpoint?

**Comment by Practicing7** [comment]
I'd like to ask you how many papers I can search at one time? When I set the limit to a number >100, the request responses with an error which says {'error': "'limit' must be <= 100"}. So if I need more papers, I have to use the offset to iterate all the papers searched manually? Or there are other ways to access to more paperIds at one time?

**Comment by cfiorelli** [comment]
@csaparna ,
Yes, you can utilize the 'Search for papers by keyword' endpoint to apply various filters to your search. For instance, you can filter by specific years of publication, fields of study, and even look for papers with open access PDFs. By using a combination of these filters, you can fetch different sets of non-overlapping papers. Here are some examples:

To search for 'covid' related papers between 2020-2023, with an open access PDF, and are either in the field of Physics or Philosophy, you can use:
https://api.semanticscholar.org/graph/v1/paper/search?query=covid&year=2020-2023&openAccessPdf&fieldsOfStudy=Physics,Philosophy&fields=title,year,authors

To get a concise result with only specific fields like URL, abstract, and authors for a 'covid' query, you can use:
https://api.semanticscholar.org/graph/v1/paper/search?query=covid&fields=url,abstract,authors

Please note there's a limitation that the endpoint can only return up to 10 MB of data at a time.



@Practicing7,

Thank you for reaching out. I'll address your questions point by point:

How many papers can I search at one time?

The API enforces a limit on the number of papers you can retrieve in a single request, and that limit is 100. Hence, when you set the limit to a number greater than 100, you're encountering the mentioned error.
Using offset to iterate through the results:

Yes, if you need more than 100 papers, you'd utilize the offset parameter to paginate through the search results. For example, for your first request, you'd set limit=100 and offset=0. For your next set of results, you'd set limit=100 and offset=100, and so forth. This allows you to iterate through all the papers that match your search criteria.
Are there other ways to access more paperIds at one time?

If your goal is to obtain a vast dataset of papers, I recommend considering our bulk download dataset API. This would provide you with extensive datasets without the constraints of the search API.
However, if you specifically want to use the search endpoint, you'll need to work with the offset and limit parameters as mentioned above. Additionally, you can strategically apply different filters to your searches to ensure you get different subsets of non-overlapping papers.
