### ISSUE TITLE
ACL Anthology: use our BibTeX files

### ISSUE THREAD

**Issue by mjpost** [allenai/s2-folks#122]
The [ACL Anthology](https://aclanthology.org) puts a lot of effort into producing correct BibTeX files for the journals and conference proceedings it hosts. This information is updated every time the site is rebuilt after a correction, for example. Consider the following example:

> Better k-best Parsing
> Liang Huang, David Chiang
> https://aclanthology.org/W05-1506/

```
@inproceedings{huang-chiang-2005-better,
    title = "Better k-best Parsing",
    author = "Huang, Liang  and
      Chiang, David",
    booktitle = "Proceedings of the Ninth International Workshop on Parsing Technology",
    month = oct,
    year = "2005",
    address = "Vancouver, British Columbia",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/W05-1506",
    pages = "53--64",
}
```

Semantic Scholar produces [a much more simplified BibTeX output](https://www.semanticscholar.org/paper/Better-k-best-Parsing-Huang-Chiang/8dfdedcbeb3b67ecaa4d85ca4b9d1aff368b8e2a):

```
@inproceedings{Huang2005BetterKP,
  title={Better k-best Parsing},
  author={Liang Huang and David Chiang},
  booktitle={International Workshop/Conference on Parsing Technologies},
  year={2005}
}
```

This distinction is understandable—we are the primary source for our material, and you're drawing from across all scientific fields. However, it would be really great if you were able to link to or pull in our BibTeX, so that Semantic Scholar users could benefit from more detailed citation information in this special case.

**Comment by cfiorelli** [comment]
This is a very interesting opportunity. I don't have immediate action here but confirming I'm moving this to internal review for 2024 priority group.
@mjpost thanks very much for sharing this insight

**Comment by mjpost** [comment]
Thanks. Our bib files should be easy for you to access since you already have the Anthology ID, but if there is anything we can do to make this easier for you, please let me know.
