### ISSUE TITLE
ACL Anthology: paper not found in Semantic Scholar, but present in Anthology

### ISSUE THREAD

**Issue by mjpost** [allenai/s2-folks#123]
**Describe the bug**

The ability to search by origin in Semantic Scholar is very nice! Strangely, [this query](https://api.semanticscholar.org/v1/paper/ACL:P96-1044) fails, despite the fact that the paper is [in the Anthology](https://aclanthology.org/P96-1044/) ([PDF](https://aclanthology.org/P96-1044.pdf)). 

You can see the whole volume on this page: https://aclanthology.org/volumes/P96-1/. This shows how the behavior is even odder, because the paper just before it ([P96-1043](https://aclanthology.org/P96-1043)) and just after it ([P96-1045](https://aclanthology.org/P96-1045/)) both behave as expected when searched for.

**Expected behavior**

It should return the JSON for paper ID P96-1044 in the Anthology.

**Screenshots**

![image](https://github.com/allenai/s2-folks/assets/455256/3a8bc718-6026-4249-9532-21976e706a55)

**Comment by cfiorelli** [comment]
Hello thanks for letting us know of this. Looks like a data issue - I'm forwarding this issue to our team feedback@semanticscholar.org
