### ISSUE TITLE
Being able to filter upon externalIds

### ISSUE THREAD

**Issue by mazzespazze** [allenai/s2-folks#125]
**Is your feature request related to a problem? Please describe.**
I would like to perform a search and exclude at priori some papers that I know I won't be interested in. 
For example filtering away Arxiv with something similar to: `"mustNotMatch": "externalIds.arxiv"` Or also that a field must exist like `mustExist:doi` or not exist `mustNotExist:doi`, `mustNotExist:externalIds.arxiv`

**Describe the solution you'd like**
A flag `filter`. As I'm assuming you use ElasticSearch behind the curtains and such filtering options are given. Assuming you index correct mapping of course.

**Describe alternatives you've considered**
At the moment the only option to filter upon query is to filter on the fly. So I am forced to ask a huge amount of papers, like 1000 at a time, filter the ones that don't match my criteria and finally get the results. But it is quite time consuming.

**Additional context**
The filtering would just give much better control over relevancy. There are so many different aspects to consider that one-algorithm fits all won't work. Though by giving access to full filtering, we can all personalize our searches. 
If you are able to create such filtering, the `openAccess` field can be included as `mustExist:pdf` or something similar. 

Thanks!

**Comment by cfiorelli** [comment]
@mazzespazze Thank you for the feedback - I've added this to a feature request analysis!
