### ISSUE TITLE
Q: Script for translating S2ORC Annotations to S2ORC-doc2json format?

### ISSUE THREAD

**Issue by maybay21** [allenai/s2-folks#126]
Hi All,

First, thank you so much for all of your hard work on the Semantic Scholar dataset. It's been invaluable to my research.

I have a quick question wrt the S2ORC dataset. I completed a bulk dataset download through the API, however the files from the API are not in the same format as the output from [S2ORC-doc2json](https://github.com/allenai/s2orc-doc2json/tree/main). I imagine this is intentional. Is there a helper script to translate the annotations into the S2ORC-doc2json format?  I received files in the format below:
 
<img width="1678" alt="recieved" src="https://github.com/allenai/s2-folks/assets/3077428/53b4b42d-7a22-42be-a944-952a28d54a6d">

My goal is to translate to the original S2ORC format:

<img width="1328" alt="expected" src="https://github.com/allenai/s2-folks/assets/3077428/eceab5fc-72d6-4568-b2d9-5173c0eeb5d5">

If there's not something on-hand, I'll hack a script together. Thanks!

**Comment by cfiorelli** [comment]
@maybay21 It sounds like by now you might have already resolved this wrt your "hack script together" + ?
Sorry for the delay here.
