### ISSUE TITLE
Dowload the full text through the "field of study" or "category".

### ISSUE THREAD

**Issue by JiaxinLIU0998** [allenai/s2-folks#128]
In the paper "S2ORC: The Semantic Scholar Open Research Corpus", Figure 2 and Figure 3 shows a distribution of paper by field of stufy/category,  so is it possible to download the full text filtering on the field of study or category  through the API ?

**Comment by Practicing7** [comment]
I'd like to ask you a question? How do you get your S2ORC API, I have requested for several times, but get no response.

**Comment by cfiorelli** [comment]
@Practicing7 - Have you checked your spam folder?

**Comment by Practicing7** [comment]
Thank you very much, it does exist in my spam folder!!

**Comment by cfiorelli** [comment]
@JiaxinLIU0998 Sorry but for the moment the only process available is to download the dataset and filter client side
