### ISSUE TITLE
Inclusion of data from clinicaltrials.gov

### ISSUE THREAD

**Issue by darrenkjr** [allenai/s2-folks#129]
**Problem**: 
Systematic reviews (particularly Cochrane reviews) include https://clinicaltrials.gov/ as a data source during evidence retrieval, and it would be great to have access to such data within the Semantic Scholar API or just searchable via the GUI.  This doesn't seem to be currently indexed by Semantic Scholar. Such clinical trials are usually not identifiable by DOI or MAG ids as well. 

**Desired Solution**
I'd like to be able to look up clinical trial information from within the Sematic Scholar API, and potentially Or be able to crosscheck co-citation networks related to a particular clinical trial. There is probably a need for a seperate identifier as clinical trials tend to use : NCTXXXXXX as the ID. 

**Alternatives I've considered**
There is an api available : https://classic.clinicaltrials.gov/api/gui, and a corresponding python wrapper : https://pypi.org/project/pytrials/, alongside a public facing search interface : https://clinicaltrials.gov/search, - but having co-citation data and trial information from a centralised source (eg: Semantic Scholar) would be a nice to have. 

**Other Context** 

At minimum, it would be nice to be able to access data from the following via the Semantic Scholar API, and there no doubt would be other applications with the inclusion of clinical trial data within the API that I haven't listed here. (Also Slack Thread)

![image](https://github.com/allenai/s2-folks/assets/45780943/64e2e6dc-25cd-4bcd-ac93-275fd2a8f39a)

**Comment by cfiorelli** [comment]
@darrenkjr 
Thank you for the suggestion and insight of this datasource to add to our corpus. 
I've added this information to a feature requests analysis.
