### ISSUE TITLE
Some papers have abstracts on semanticscholar.org but not in the API

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#13]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/1858803/225952251-11c1a633-921c-4da0-9c90-3cb5a4514618.png">

**Comment by wammar** [comment]
I'm afraid this is the expected behavior, due to legal constraints on what we can redistribute. We should update our documentation to reflect this. I'll keep this open until we fix the documentation.

**Comment by Androbin** [comment]
Is it possible to look up the publisher partner, data provider, or aggregator providing Semantic Scholar with the abstract for a given paper?

**Comment by wammar** [comment]
> Is it possible to look up the publisher partner, data provider, or aggregator providing Semantic Scholar with the abstract for a given paper?

@Androbin Not possible right now, unfortunately. Let me create a new issue for this feature request and close this one.

**Comment by bingohuang** [comment]
I also encountered the problem, some papers have abstracts on semanticscholar.org but not in the API and datasets. 
How did you get the acstract on semanticscholar.org? Is authorization required?
Thank you very much.@wammar
