### ISSUE TITLE
Q: Are paper-embedding-public-apis part of the Semantic Scholar APIs?

### ISSUE THREAD

**Issue by de-code** [allenai/s2-folks#132]
I am interested in using [paper-embedding-public-apis](https://github.com/allenai/paper-embedding-public-apis).
But I am not quite sure what the expected availability is.
Should I also pass in the API key to that API?

**Comment by cfiorelli** [comment]
@de-code 
Hello and thank you for the question.
It looks like you're seeking to use Specter with S2. We just published news for using Specter in our official [release notes](https://github.com/allenai/s2-folks/blob/main/API_RELEASE_NOTES.md) as follows:

**Specter2 embeddings**

AI2’s SPECTER 2.0 is the latest version of our document embedding models designed specifically for scientific tasks. Building upon its predecessor, SPECTER is tailored to generate embeddings for specific tasks, such as Classification, Regression, and Proximity. The API serves pre-computed Proximity embeddings, appropriate for computing the similarity between two documents.
The model is hosted as [allenai/specter2](https://huggingface.co/allenai/specter2) on HuggingFace, along with the models for other task-specific embeddings.


Could you review and confirm this resource aligns with what you're looking for?

**Comment by de-code** [comment]
Thank you for getting back to me. I understand I could use the model via HuggingFace.
My original question was more around the [API offered to get embedding for title and abstract](https://github.com/allenai/paper-embedding-public-apis). e.g. for papers that aren't currently available via the [S2 Graph API](https://api.semanticscholar.org/api-docs/graph).
Is that API properly supported by S2 or is it just meant for research?
And now that you switched to offering SPECTER 2, will [that API](https://github.com/allenai/paper-embedding-public-apis) get updated to support that too?

**Comment by cfiorelli** [comment]
Looks like the embedding page is not under s2 nor scholar and is probably not supported by S2.
As a result of S2 not being the managers of that repo I can't say when or if it would receive the v2 model. 

I did notice at the bottom there is a comment about submitting questions directly on that repo - if you end up trying that let me know if that helps. 
best
