### ISSUE TITLE
Exporting Library.

### ISSUE THREAD

**Issue by krishanrana** [allenai/s2-folks#137]
**Is your feature request related to a problem? Please describe.**
I would like to export the library including collections I have created so that I can import into Zotero.

**Describe the solution you'd like**
Some way to interface SS with Zotero. As a start if you could allow me to export my saved library in zotero so that I can sync it with SS.

**Describe alternatives you've considered**
Research Rabbit and Zotero.

**Comment by LunarEngineer** [comment]
This is something that I'm very interested in; I'm currently looking to automate my research process and would very much like to use my Semantic Scholar library as the source data that feeds the automation.

I know there are ways to export that data manually; I'm very interested in any potential automation opportunities.

**Comment by cfiorelli** [comment]
@LunarEngineer @krishanrana 
Thanks everyone for bringing visibility to this idea. I'm not aware of an API method to extract S2 user library data, but to better understand this from a feature request perspective could to describe a little detail on the use case/research process?

Thank you

**Comment by LunarEngineer** [comment]
Morning @cfiorelli.

My use case involves me interacting with SS as a researcher and saving items to collections in my SS library.

At some point (INTEGRATION POINT) my SS library will be exported to a tabular dataset; that dataset will be scraped and used to populate a secondary data source (Notion) which is intended to mirror, present, synthesize, and summarize the SS library.

The INTEGRATION POINT (right now) is a manual process; there's value for me in automation involvement at this point.

Please let me know if this gives you enough information to help work through a feature request.

**Comment by cfiorelli** [comment]
Thank you @krishanrana @LunarEngineer 
I'm taking your comments to our feature request review process.

**Comment by cfiorelli** [comment]
Closing out here as next step is in progress - connecting with both of you to gather hands-on understanding of the requirements.
