### ISSUE TITLE
Half of the citations are missing in recent bulk downloads

### ISSUE THREAD

**Issue by aletar89** [allenai/s2-folks#138]
Hi team,
We've noticed the citations bulk download has less citations than usual. The 2023-07-04 corpus had 2.1E9 citations but 2023-08-15 has only 0.9E9 citations. 
I think there was a similar event in the past were half the citations disappeared and then returned after a couple of releases but this time it's been this way for a couple of releases already.

**Comment by rodneykinney** [comment]
Those counts don't match what we see on our side. These numbers come from querying the released `.json.gz` files:

```
release	is_matched	count
2023-07-04	true	2238231599
2023-07-04	false	337395225
2023-08-15	true	2262533935
2023-08-15	false	332121203
```
(`is_matched` means `citedpaperid IS NOT NULL`)

**Comment by aletar89** [comment]
Seems to have resolved itself. Maybe the issue was on our side though we didn't find anything to fix, just re-ran it a couple more times and now we get the same numbers as you.
