### ISSUE TITLE
Does the API provide paper full text?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#14]
> Hi! I had a quick question about the Semantic Scholar API: is there a part of the API that I can connect to where it contains all the text in the research papers? I noticed there are datasets for headers, dates, authors, references, but I'm not sure if I missed the one that included the text in its entirety in research papers. Thanks!
> Feedback was from https://www.semanticscholar.org/product/api
> 

From [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/55944)

**Comment by Androbin** [comment]
GROBID yields amazing semantically annotated output but it can be hella slow.

It would be awesome if you Allen AI folks could pre-compute its output for all your papers ahead of time.

**Comment by 37david** [comment]
Thanks for your question! I am also looking into it now. Have you got any ideas about how to download the full text of papers

**Comment by jaronjaron** [comment]
We do have the S2ORC dataset available to download, which includes full-body paper text parsed from open-access PDFs. It also identifies structural elements such as paragraphs, sections, and bibliography entries (which is currently done via Grobid).

https://api.semanticscholar.org/datasets/v1/release/latest

![Image](https://user-images.githubusercontent.com/1452635/232882676-a0bb0e39-ccf4-41e0-9ef3-5bf83c65034b.png)

**Comment by wammar** [comment]
Thank you @Androbin and @jaronjaron for helping out with this issue.
