### ISSUE TITLE
Journal title missing for ChemRxiv

### ISSUE THREAD

**Issue by pwrose** [allenai/s2-folks#152]
**Describe the bug**
The journal name is missing for ChemRxiv

**To Reproduce**
https://api.semanticscholar.org/graph/v1/paper/10.33774/chemrxiv-2021-nd0r2-v2?fields=journal

returns:
{"paperId": "87180cbca685bec92f14c94af69015b33c3f5002", "journal": null}

**Expected behavior**
The journal name should be ChemRxiv.

**Comment by cfiorelli** [comment]
Flagging for data corrections for 2023 retro
Thank you for the report
