### ISSUE TITLE
Q: what is the input limit for recommendations based on multiple papers

### ISSUE THREAD

**Issue by renespijker** [allenai/s2-folks#153]
Wait! 🤚 Before creating this issue, please read carefully: We want to enable our partners (that's you) to succeed, but our team has limited bandwidth for answering your questions. In order to help us help you more efficiently, kindly spend 2 minutes to check:
* is your question [already addressed in the FAQs page](https://github.com/allenai/s2-folks/blob/main/FAQ.md)?
* is your question [already asked in another ticket](https://github.com/allenai/s2-folks/issues?q=is%3Aissue+label%3Aquestion)? You can filter the issues by adding salient words from your question. You're always welcome to reopen a related question and add a comment to provide more nuances that are relevant to your use case. 

... it's OK if you missed something and end up asking something we addressed before, but we might tease you about it a little bit 😉

We're committed to taking action on your issue within 7 days and responding within 10 days. If you don't get a response within 10 days, If we don't address your question in 7 days, please post it on [slack](https://semanticschol-xyj3882.slack.com/ssb/redirect) to bring our attention to it.

**Comment by renespijker** [comment]
Q: I'm looking at the recommendation API (https://api.semanticscholar.org/api-docs/recommendations) for a list of papers. It is working but somehow I can not find what the maximum input papers are (experimentally im running against a limit around 100 papers after which I get an error 400 code returned. At fist I though I could use the limit code to change this but that is only for the number of output documents. As I'm trying this out for building a continuous updating repository I was wondering how to go about this when the number of documents in the repository exceeds 100?

**Comment by cfiorelli** [comment]
Moving to Backend to triage 
- eval increase to limits
- ensure documentation clarifies limits

**Comment by cfiorelli** [comment]
@renespijker Could you confirm you're still running into this 100 input ceiling? 
I'm taking a look to identify input limits which seem to be quite a bit higher than this - but i'm still digging to understand this part of our structure
