### ISSUE TITLE
CitationStyles output missing data

### ISSUE THREAD

**Issue by renespijker** [allenai/s2-folks#154]
when the API for recommendations is used and as an output citationStyles is checked it produces a bib format but doesn't include all citation information such as doi, URL, etc which makes the reference very incomplete and not very useable. preferably includes abstract doi, web address etc

**Comment by renespijker** [comment]
this would enable a direct import into reference management systems, etc

**Comment by cfiorelli** [comment]
Marking here as relevant to #122
