### ISSUE TITLE
Q: On /paper/batch is the order of returned papers guaranteed to match the request order?

### ISSUE THREAD

**Issue by PedroSena** [allenai/s2-folks#158]
Hi folks,

Assuming I request 3 papers A,B and C, using the `/paper/batch` endpoint, is it guaranteed that the response will respect that order ? I ask you that mainly because of the paper rerouting/deduplication mechanism Semantic Scholar has. For instance let's assume paper B and C return data for papers X and Y due to rerouting:

| Requested Paper ID | Returned Paper ID |
|--------|--------|
| A | A |
| B | X |
| C | Y |

Is it guaranteed that paper X is a rerouting for paper B and *not* a rerouting for paper C ? We are trying to capture those reroutings that Semantic Scholar does and having some trouble to identify the proper metadata to do it.

Thanks in advance,

**Comment by PedroSena** [comment]
To follow up:

I found this issue that seems related https://github.com/allenai/s2-folks/issues/47 but it is not clear whether this was fixed or simply was closed as being a duplicate (I suppose the linked repository is not public, thus resulting in 404)

**Comment by cfiorelli** [comment]
@PedroSena - There is a considerable "rabbit hole" of related issues internally and externally associated to this, and they're all closed - and seem "working as intended, but not documented clearly". 
If you're still impacted here could you please confirm back and share an update on details?
