### ISSUE TITLE
S2AG API: Search endpoint is down

### ISSUE THREAD

**Issue by shauryr** [allenai/s2-folks#16]
[https://api.semanticscholar.org/graph/v1/paper/search?query=literature+graph](https://api.semanticscholar.org/graph/v1/paper/search?query=literature+graph)

this doesn't seem to work right now. I am getting a - "Endpoint request timed out". Did I reach limit on my API usage?

**Comment by JannKleen** [comment]
We're having the same issue.

**Comment by wammar** [comment]
Thanks @shauryr! Our on-call team is on it.

**Comment by rodneykinney** [comment]
The timeouts are affecting all users, caused by excessive bot traffic. We are working to identify and block the offending sources.

**Comment by shauryr** [comment]
seems to be working now

**Comment by rodneykinney** [comment]
Response times are still elevated, although they won't necessarily time out.

**Comment by rodneykinney** [comment]
Latency is back within tolerance.
