### ISSUE TITLE
FR: TLDR as returned field in /paper/search/bulk?

### ISSUE THREAD

**Issue by rwst** [allenai/s2-folks#161]
**Is your feature request related to a specific use case or dataset?**
Concerning the /paper/search/bulk endpoint.

**Problem Statement**
/paper/search/bulk can return title and abstract, but not TLDR

**Proposed Solution**
Include TLDR as returned field.

**Benefits & Impacts**
Around 40 per cent of biomedical  papers don't have an abstract, so results returned from /paper/search/bulk on them are not very usable and need a second query to get at least the TLDR.

**Alternative Solutions Considered**
As said above there is the workaround of a second call but it would help also if /paper/search/bulk would search in TLDR too even if TLDR is not returned.

**Comment by sadovsd** [comment]
What does you workaround look like? I'm currently only able to retrieve one paper tldr at a time using this endpoint https://api.semanticscholar.org/graph/v1/paper/{paper_id}, which takes forever. Is it possible to retrieve multiple tilde's at once? The documentation says this endpoint can return up to 10 MB of data at a time, which should imply that it can return info about multiple papers, but I don't know how to make it work. Sorry about my limited experience to all of this...

**Comment by rwst** [comment]
Get an API key to get fields for bulk of papers. See the API docs for the bulk endpoint.

**Comment by cfiorelli** [comment]
Thanks for your report here
- logging this for optimizations to data team
