### ISSUE TITLE
Q: how are citation results ordered?

### ISSUE THREAD

**Issue by keller-mark** [allenai/s2-folks#166]
I am using the citations API to get a list of citations for a paper. This paper has over 10,000 citations but I understand that I can only access up to 10,000 results via the API. I am wondering if the results are ordered in a particular way that would make those first 10,000 citations biased (e.g., temporally biased toward older citations?). Thanks!

**Comment by cfiorelli** [comment]
@keller-mark are you working with https://api.semanticscholar.org/graph/v1/paper/{paper_id}/citations
or our bulk endpoints?
