### ISSUE TITLE
Q: How are our search queries collected and used by S2?

### ISSUE THREAD

**Issue by qzhou-sonatatx** [allenai/s2-folks#169]
Are our search queries accessible by a third-party for marketing or other purposes?

Please check for existing answers to your question:
* [The FAQs page](https://github.com/allenai/s2-folks/blob/main/FAQ.md)
* [Existing tickets](https://github.com/allenai/s2-folks/issues?q=)
* [Our Slack community](https://semanticschol-xyj3882.slack.com/ssb/redirect) 

Before posting your question here, please consider if it's appropriate for our Slack community. For quick queries and discussions, our Slack community tends to be more responsive. We reserve GitHub issues primarily for larger, more complex inquiries or those pertaining to technical issues.

Question

[Please provide a clear and concise description of your question.]

Context (Optional)

[If applicable, add context or background about your question. For instance, what led you to ask this?]

Additional Information (Optional)

[Include any other relevant information or screenshots related to your question.]

**Comment by cfiorelli** [comment]
@qzhou-sonatatx Queries are not made available to third parties.
Thanks for the question.
