### ISSUE TITLE
API returning empty responses.

### ISSUE THREAD

**Issue by JannKleen** [allenai/s2-folks#17]
Since 17th of March, the API seems to be returning empty responses in 10% of our users' searches. This is new behaviour (we didn't account for that in our code and no errors were raised until then). Did something significant change or is this a bug? The response we get is:
```
{
offset: 0, 
total: 0
}
```

**Comment by wammar** [comment]
@JannKleen Sorry for the delay addressing this issue. Could you provide repro details, i.e., API call and the full HTTP response (including error message in case of a failure)?

**Comment by wammar** [comment]
Closing this assuming it was a transient issue that no longer needs to be addressed.

@JannKleen if not, please feel free to reopen to provide repro details, i.e., API call and the full HTTP response (including error message in case of a failure).
