### ISSUE TITLE
General search endpoint (including title, authors, journal...)

### ISSUE THREAD

**Issue by straeter** [allenai/s2-folks#170]
Hi,
it would be great to have a search endpoint that looks for a general matching of the metadata, like title, authors, journal... and gives the most likely results. This would be great e.g. when I have some bibliographic data which are often not coherent but usually contain enough information to find the paper unambiguously on semanticscholar.

Actually there is the manual search on the main page: https://www.semanticscholar.org/ but I have not found a respective endpoint for the api.

I tried the query completion and the relevance search but looks like they only work for titles / keywords, whereas the manual search also gives me the right result if I only enter the author names and the journal.

Would this be possible?
Cheers

**Comment by cfiorelli** [comment]
@straeter have you tried the bulk search endpoint - this might resolve the need here. https://api.semanticscholar.org/graph/v1/paper/search/bulk

let us know thank you

**Comment by straeter** [comment]
> @straeter have you tried the bulk search endpoint - this might resolve the need here. https://api.semanticscholar.org/graph/v1/paper/search/bulk
> 
> let us know thank you

@cfiorelli thanks, yes I tried the bulk search but as I understand it can only match the search term against title and abstract, not on authors and journal and one cannot order the results by relevance (which would be crucial for the usecase I described).

Whatever search mechanism the manual semanticscholar web search uses, this would be very helpful as an API endpoint

**Comment by cfiorelli** [comment]
Ah i see. I suppose you might construct this by downloading datasets and performing filtering and searching.

For a new endpoint we can take this down as a possible feature request. Thank you
