### ISSUE TITLE
Q: How search query should be constructed for combination of keywords without limiting results?

### ISSUE THREAD

**Issue by mnikor** [allenai/s2-folks#172]
If I use in PubMed this query to find real world evidence studies **"real world evidence" OR "observational study" OR "registry" OR "case-control" OR "cohort study" OR "cross-sectional" OR "pragmatic trial" OR "eHR data" OR "Claims database"**  I find   more than 1,5 mln abstract but if I do the same in Semantic Scholar result are very limited.

This  combination is important as all  of them relate to real world evidence studies but only one or two can appear as combination in specific abstract. For example it could include "cross-sectional retrospective" study without "real world evidence".

**Comment by cfiorelli** [comment]
@mnikor Are you working with this query structure in paper bulk search? the "OR" is not supported - please refer to docs at https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/get_graph_paper_bulk_search

**Comment by mnikor** [comment]
thanks, I tried  using "|" instead of " OR"   here is example I used:  "retrospective | cross-sectional | real world | eHR | Claims database | case-control | Registry | non-interventional study"  but still this query restricts results. For example I get only 256 publications from this search while if I use only "retrospective" in search I get 14000000 results.   Perhaps I do something wrong?
