### ISSUE TITLE
Q: Is it possible to get bulk paper data in structure CSV format  for specific field and disease?

### ISSUE THREAD

**Issue by mnikor** [allenai/s2-folks#173]
I need Data with all Metadata available for specific disease like Prostate cancer. Can I do bulk download  for this disease only in CSV file and also for specific period (last 3 years for example)

**Comment by cfiorelli** [comment]
In python you could convert the response to csv as a step before writing to file. We don't offer directly any csv formatted data in the api. Hope this helps!
