### ISSUE TITLE
Bug: No recommendations for papers

### ISSUE THREAD

**Issue by BastienLeGuellec** [allenai/s2-folks#176]
Hi,

I am using the Recommendations API with different input papers (for example, but not limited to (PMID) 20548009,  15847617, 15983302, 8664139). The input is:

https://api.semanticscholar.org/recommendations/v1/papers/forpaper/PMID:15847617 (or any of the PMID on the list)

The output is :

recommendedPapers	[]

The output is the same when converting these PMID in semanticscholar ID.
The API works fine with other inputs.
The said papers have related articles suggested on the semantic scholar website.

So you have any ideas how to solve this issue?

Thanks a lot!

Bastien

**Comment by cfiorelli** [comment]
Thank you for your report @BastienLeGuellec 
This appears to be a data pipeline team item - flagging to for triage here.
