### ISSUE TITLE
Q: How to get the full-text of the paper via S2 API?

### ISSUE THREAD

**Issue by realliyifei** [allenai/s2-folks#177]
Do the S2 API or S2ORC dataset provide the full-text of the papers (at least the open accessible ones)? I don’t think [the fields in API](https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/get_graph_get_paper) contain the full text of any paper.

**Comment by cfiorelli** [comment]
Correct, to work with full text, you will use our S2ORC dataset
