### ISSUE TITLE
Q: download the whole semantic scholar dataset?

### ISSUE THREAD

**Issue by realliyifei** [allenai/s2-folks#178]
Is there a quick way to download the latest version of the whole semantic scholar dataset, including the full texts as many as possible, to the local?

**Comment by cfiorelli** [comment]
You will use the datasets API.
- developer documentation can be found here: https://api.semanticscholar.org/api-docs/
- please see python examples containing the word "Datasets" here: https://github.com/allenai/s2-folks/tree/main/examples/Webinar%20Code%20Examples
- some content for datasets is also available on our tutorial page here: https://www.semanticscholar.org/product/api/tutorial#datasets
