### ISSUE TITLE
Q: how to join the slack?

### ISSUE THREAD

**Issue by realliyifei** [allenai/s2-folks#179]
The GitHub suggests to visit the [Slack community](https://semanticschol-xyj3882.slack.com/ssb/redirect) but I cannot find a way to join it. My slack email is liyifei@seas.upenn.edu.

**Comment by cfiorelli** [comment]
@realliyifei Please proceed to this URL to join our Slack community: https://join.slack.com/t/semanticschol-xyj3882/shared_invite/zt-2404ykgp1-UQMhlKNR71crDEEEldDjNg
Looking forward to seeing you there!
