### ISSUE TITLE
API Request Timed out & Internal Server Error

### ISSUE THREAD

**Issue by Alaamoheb** [allenai/s2-folks#18]
I'm getting the two messages:
{'message': 'Internal Server Error'}
{'message': 'Endpoint request timed out'},
how to fix this error?

**Comment by shauryr** [comment]
https://github.com/allenai/s2-folks/issues/16 - the team is working on it.

**Comment by jaronjaron** [comment]
Closing since the previously linked issue has been resolved. Please open a new ticket if you still have issues.
