### ISSUE TITLE
Q: Can we get the full text of a specific paper by searching corpusID in s2orc dataset?

### ISSUE THREAD

**Issue by SeanZh30** [allenai/s2-folks#184]
Hello, I haven't found a solution to this after checking the existing issues. If I want to use corpusid to find the full text of a paper in the s2orc dataset (like an entire row), can we search it through the API? Or do you have to download the entire data set to do the filter? Thank you for your answer.

**Comment by cfiorelli** [comment]
Have to use datasets. thank you for the question !
