### ISSUE TITLE
Bug: What happened to the S2 API server? Is the server under attack?

### ISSUE THREAD

**Issue by hrbust-zlz** [allenai/s2-folks#185]
**Describe the Bug**
I failed on requesting entry https://api.semanticscholar.org/graph/v1/paper/search.
For unauthenticated users, the response is status code 429.
When I try the python example in [https://www.semanticscholar.org/product/api/tutorial#key](url) with my own API key, the response is status code 500 or 504.
I tried a manual search of keyword "quantum computing" on the webpage https://www.semanticscholar.org/, the "matching papers" recommendation works, but the search result shows error code 502 or 504.
The webpage https://api.semanticscholar.org/api-docs/ is also influenced, it shows a message "Too Many Requests. Please wait and try again or apply for a key for higher rate limits. https://www.semanticscholar.org/product/api#api-key-form" in the browser. It's a status code 429 too.

**To Reproduce**
Even the python example in [https://www.semanticscholar.org/product/api/tutorial#key](url) does not work...

**Expected Behavior**
At least return a status code 200 please...

**Actual Behavior**
The API returns status code 500 or 504.

**Environment Details**
Platform: Windows 10 22H2
Browser: Google Chrome 122.0.6261.95

**Comment by jamesbraza** [comment]
+1 to this, I think it's an uncaught downtime. I also think the [status page](https://status.api.semanticscholar.org/) should check this endpoint, to better assess for downtime

**Comment by cfiorelli** [comment]
Hello everyone,
We are working to manage a large spike in traffic which occurred overnight. 
We have observed in this and a similar very recent event that the status page is not capturing this type of traffic event. Work will be planned and actioned to reflect these unique events as a part of our efforts to improve over the near to mid term.

Please be aware you can also participate or simply monitor discussion via our slack community at https://join.slack.com/t/semanticschol-xyj3882/shared_invite/zt-2404ykgp1-UQMhlKNR71crDEEEldDjNg

thank you all.
Christopher, Semantic Scholar

**Comment by jamesbraza** [comment]
Hi Christopher, apparently the Slack is only for people with certain email domains. I don't have one of those :/ so I can't join. I want to join though

<img width="445" alt="screenshot of slack allowed email domains" src="https://github.com/allenai/s2-folks/assets/8990777/d55cdd0e-8b47-4391-9774-281613661bd1">

Can you expand the Slack to allow for other domains?

**Comment by cfiorelli** [comment]
Hmm this is not how that should behave. 1 moment checking into this

**Comment by cfiorelli** [comment]
I see slack started (or always has?) rotating the invite link in a way which
- a new link has 30 days and allows any email
- [assumption from above] past 30 days the link rotates into requiring only some domains (which i lack backstory on why this is)

@jamesbraza here's an updated link which should work

**Comment by jamesbraza** [comment]
@cfiorelli thanks for investigating. Your last comment doesn't have a Slack invite link, did you forget to paste one into the message?

**Comment by cfiorelli** [comment]
@jamesbraza thanks for letting me know. earlier comment updated!

**Comment by jamesbraza** [comment]
I was able to join, thanks 👍

**Comment by hrbust-zlz** [comment]
> Hello everyone, We are working to manage a large spike in traffic which occurred overnight. We have observed in this and a similar very recent event that the status page is not capturing this type of traffic event. Work will be planned and actioned to reflect these unique events as a part of our efforts to improve over the near to mid term.
> 
> Please be aware you can also participate or simply monitor discussion via our slack community at https://join.slack.com/t/semanticschol-xyj3882/shared_invite/zt-2404ykgp1-UQMhlKNR71crDEEEldDjNg
> 
> thank you all. Christopher, Semantic Scholar

Now the entry https://api.semanticscholar.org/graph/v1/paper/search behaves as expected, but when I request for paper details (e.g., https://api.semanticscholar.org/graph/v1/paper/12e668ad61fbcfb1e4752f1243082dc8c0f75f4f?fields=paperId%2Ctitle%2Cvenue%2Cyear%2Cauthors%2CexternalIds%2Cabstract%2CopenAccessPdf%2Ctldr%2CcitationStyles) with my API Key, it still returns status code 500. Also, code 429 for unauthenticated users.

**Comment by cfiorelli** [comment]
Closing as we have responded with information regarding ongoing work happening at Semantic Scholar to recover from heavier traffic than usual + a link to join our slack community where users can more easily monitor updates:
https://join.slack.com/t/semanticschol-xyj3882/shared_invite/zt-2e6vky451-fmp5TyRlRoeOzk0rov7MUA
