### ISSUE TITLE
FR: When download S2ROC dataset, can we specify the field of study in the API request? 

### ISSUE THREAD

**Issue by ziyueyang37** [allenai/s2-folks#188]
When download the S2ROC dataset from API, I want to only include the papers for a specific field of study, ex. quantum chemistry, I don't see a way of doing that since the request return a list of links that download the chunks, is there a way of doing that?

**Comment by cfiorelli** [comment]
You're correct - the files are pre constructed and would have to be filtered down via client side processing.

Thanks for the question !
