### ISSUE TITLE
API requests from cloud server gives Internal Server Error, but requests from local machine works fine.

### ISSUE THREAD

**Issue by phongnguyen-aveksana** [allenai/s2-folks#19]
Hi, I am aware of #16. Problem for me is when I send requests from my cloud server (Azure), it gives Internal Server Error almost every time, but when I send requests from my local machine it never fails. I wonder if this is because of some blocking mechanism that you are using to fight the DDoS. If you have any idea about this case please contact me, I would like to solve this ASAP for our product testing.

**Comment by yvonne-chou** [comment]
Closing
