### ISSUE TITLE
Bug: duplicate IDs in `/graph/v1/paper/abc123/citations`

### ISSUE THREAD

**Issue by jamesbraza** [allenai/s2-folks#190]
**Describe the Bug**

On 3/27/2024, https://api.semanticscholar.org/graph/v1/paper/4f51307e3bed55b21664b91a894f2a7075b841b2/citations
had a duplicate ID `958353e2764f50251b0620295de9a7f1af2a8b62`.

As of 4/8/2024:
- The total number of results in `/citations` has grown, which means the Semantic Scholar internal data has since changed
- The duplication of `958353e2764f50251b0620295de9a7f1af2a8b62` no longer persists

I am reporting this bug because I believe whatever updates the internal data has the possibility to introduce duplicate IDs

**Screenshots**

N/a

**Environment Details**

N/a

**Comment by cfiorelli** [comment]
flagging for data pipeline team
thanks so much for the report @jamesbraza
