### ISSUE TITLE
Q: S2ORC bulk download

### ISSUE THREAD

**Issue by flckv** [allenai/s2-folks#192]
How to download full-text of S2ORC dataset as bulk?

**Comment by cfiorelli** [comment]
@flckv 
Please have a look at our Dataset resources
1. https://github.com/allenai/s2-folks/tree/main/examples/Webinar%20Code%20Examples
2. https://www.semanticscholar.org/product/api/tutorial#datasets

hope this helps - if you need more assistance we can reconnect. best
