### ISSUE TITLE
Affiliation requirements 

### ISSUE THREAD

**Issue by Alaamoheb** [allenai/s2-folks#20]
Doesn't The API support the affiliation? 
if not, any idea what I should do if I want to fetch data for a specific affiliation!

**Comment by wammar** [comment]
Author affiliation can be obtained using the `affiliations` field in the endpoint https://api.semanticscholar.org/graph/v1/author/, e.g.,

```
// 20230423134752
// https://api.semanticscholar.org/graph/v1/author/145585097?fields=affiliations

{
  "authorId": "145585097",
  "affiliations": [
    "Allen Institute for Artificial Intelligence (AI2)"
  ]
}
```

See detailed documentation for this endpoint [here](https://api.semanticscholar.org/api-docs/graph#tag/Author-Data/operation/get_graph_get_author)
