### ISSUE TITLE
Q: Can I please get an updated invite to the Slack? 

### ISSUE THREAD

**Issue by BoracicNards** [allenai/s2-folks#207]
I have some quick questions that seem to be out of the GitHub issues scope, however it is saying I need to have an email for a certain domain when trying to join from old invite links.

**Comment by cfiorelli** [comment]
Here's the link that _should_ work. https://join.slack.com/t/semanticschol-xyj3882/shared_invite/zt-2e98pwubp-vzoxaTgITyurw~~WK1OntQ

Please reopen/message if this doesn't work 

thanks !
