### ISSUE TITLE
Q: Rate limits for no api key

### ISSUE THREAD

**Issue by erolmk** [allenai/s2-folks#208]
What are the existing rate limits for the API without an API key? I read that it is 1RPS but I am currently not experiencing that. It seems that there is limited amount of requests I can make within a certain length of time (like an hour or something), and also I get the 429 Error even when using a 1.1 second delay between requests.

**Comment by cfiorelli** [comment]
Without an API key the best quality possible is 1RPS, this pulls from a shared pool of request per some time frame which is not possible to define since its shared among all unauthenticated requestors.
