### ISSUE TITLE
Bug: Mismatch in search results for web search vs API search

### ISSUE THREAD

**Issue by akila-peiris-cml** [allenai/s2-folks#210]
**Describe the Bug**
The results obtained from web search and the API search yield different results. And more often than not, the results in the API are worse. I should also mention that this is the case even without even having hypens in the query.

I have also read [this](https://github.com/allenai/s2-folks/issues/42) issue/ feature request and it says the APIs have been reconciled 
![image](https://github.com/user-attachments/assets/ec4eb2ab-053e-4ff7-8186-1b96faa67ee8) but the issue remains at large.

**To Reproduce**
Perform a search in the web UI, and do the same using API.
The total number of results as well as the results themselves are different between the 2 searches.
API typically gives worse results

**Expected Behavior**
I expected the API and the web UI search to produce the same results.

**Actual Behavior**
The API results are almost always lower in total number and sometimes the obtained results are drastically different and much worse compared to the web UI

**Screenshots**
Search Phrase: Impact of LLM based interventions on softskill development

Web UI URL: https://www.semanticscholar.org/search?q=Impact%20of%20LLM%20based%20interventions%20on%20softskill%20development&sort=relevance&pdf=true
![image](https://github.com/user-attachments/assets/17353ccd-872a-4100-88fd-28cd678afb66)

API URL: 'https://api.semanticscholar.org/graph/v1/paper/search?query=Impact%20of%20LLM%20based%20interventions%20on%20softskill%20development&limit=100&offset=0&openAccessPdf=True&isOpenAccess=True'
![image](https://github.com/user-attachments/assets/06eaa6b3-825f-4428-b8b9-cd7a822bd712)

Observe how the total results are different.
This was just a small example on something I was working on right now. But I have observed that for some phrases, the different between total number of results can differ by a couple of magnitudes as well.

**Comment by cfiorelli** [comment]
@akila-peiris-cml 
Thank you for this. We do have a long running understanding here that the web app and its results are built sufficiently differently than the API. While we hope API search is useful we do also have to guide users that any attempt to align the API results to the web results will be not useful.
