### ISSUE TITLE
Q: Does the endpoint bulk suppot the feature 'offset'?

### ISSUE THREAD

**Issue by Junjie-Chu** [allenai/s2-folks#213]
Please check for existing answers to your question:
* [The FAQs page](https://github.com/allenai/s2-folks/blob/main/FAQ.md)
* [Existing tickets](https://github.com/allenai/s2-folks/issues?q=)
* [Our Slack community](https://semanticschol-xyj3882.slack.com/ssb/redirect) 

Before posting your question here, please consider if it's appropriate for our Slack community. For quick queries and discussions, our Slack community tends to be more responsive. We reserve GitHub issues primarily for larger, more complex inquiries or those pertaining to technical issues.

Question

I would like to know if the bult endpoint has a similar feature 'offset' like the paper search endpoint? 

Context (Optional)

I would like to fetch 10k papers from bulk endpoint, however, I find bulk always gives me the 1rd - 1000th paper, I cannot get the 1001th - 10000th paper. I try to add the 'offset' but it does not work.

Additional Information (Optional)

I use the official example: https://github.com/allenai/s2-folks/blob/main/examples/Webinar%20Code%20Examples/API_Bulk_Search.py

**Comment by cfiorelli** [comment]
The /paper/search/bulk endpoint does not support an offset parameter like the regular /paper/search endpoint. Instead, the bulk endpoint uses a pagination token to retrieve the next batch of results.

How to Fetch More Than 1,000 Papers:
Initial Request:

Make your first request to /paper/search/bulk with your desired query parameters.
The response will include a continuation token if there are more than 1,000 results.
Subsequent Requests:

Use the provided continuation token in the token parameter of your next request to get the next batch of papers.
Continue this process, using the latest continuation token from each response, until you have retrieved all desired results.
Example Workflow:


**First Request:**
```
curl -X POST "https://api.semanticscholar.org/graph/v1/paper/search/bulk" \
-H "Content-Type: application/json" \
-d '{
      "query": "machine learning",
      "limit": 1000
    }'

```

**Handling the Response:**
The response will contain a token field if there are more papers available.
Use the continuation token from the previous response:

```
curl -X POST "https://api.semanticscholar.org/graph/v1/paper/search/bulk" \
-H "Content-Type: application/json" \
-d '{
      "query": "machine learning",
      "limit": 1000,
      "token": "your_continuation_token_here"
    }'
```

Repeat these steps, updating the token value each time, until the response no longer includes a continuation token.
Let me know if you need further clarification or help!
