### ISSUE TITLE
Q: How to activate a disabled API key?

### ISSUE THREAD

**Issue by wylapp** [allenai/s2-folks#214]
Please check for existing answers to your question:
* [The FAQs page](https://github.com/allenai/s2-folks/blob/main/FAQ.md)
* [Existing tickets](https://github.com/allenai/s2-folks/issues?q=)
* [Our Slack community](https://semanticschol-xyj3882.slack.com/ssb/redirect) 

Before posting your question here, please consider if it's appropriate for our Slack community. For quick queries and discussions, our Slack community tends to be more responsive. We reserve GitHub issues primarily for larger, more complex inquiries or those pertaining to technical issues.

Question

I have not utilized my API key for some time. Now, I have found that it is disabled. Is there any way by which I can reactivate my API key? 

Context (Optional)

NA

Additional Information (Optional)

NA

**Comment by cfiorelli** [comment]
@wylapp 
Thank you for your interest in reactivating your key. We are currently blocked on new keys, key modifications and reactivations due to in progress system and process change work. 

I will leave this ticket open so that as we move ahead we can follow up with each other to reinstate your key once our processing is back up.

**Comment by pournaki** [comment]
> once our processing is back up

Would you mind providing an estimate of how long this will take?

**Comment by cfiorelli** [comment]
I'm not able to produce any estimate as our next steps toward restart aren't yet clear.

**Comment by pournaki** [comment]
Thank you for the reply. Is there any other way to access the S2ORC dataset in the meantime?

**Comment by cfiorelli** [comment]
In the products I manage I believe there is currently no other option. I did some googling and found : https://huggingface.co/datasets/sentence-transformers/s2orc

Hopefully this helps! Cheers.

**Comment by pournaki** [comment]
Thanks!

**Comment by akhilkedia** [comment]
As this issue is now closed, can API keys be re-activated again now, or is this still blocked? My API key was disabled due to inactivity, and I would like to re-activate it.

**Comment by wylapp** [comment]
> As this issue is now closed, can API keys be re-activated again now, or is this still blocked? My API key was disabled due to inactivity, and I would like to re-activate it.

My key is still being suspended, and according to the  SS webpage, new API Key application is not accepted at the moment. Really frustrated :-(
