### ISSUE TITLE
Q: I have submitted the partner request form more than five days

### ISSUE THREAD

**Issue by CaiJirui-0524** [allenai/s2-folks#215]
Hello, 
I submitted the request on 11th October. And yesterday, 14th October, I filled the table and applied the API key again. However, I have not received the reply e-mail untill now, it's also not in my spam folder. In addition, my account can not log in the freshdesk, which I found its link in previous Q&A bank,#46, to check the status of my application. 

My e-mail: 2024210301002@mails.zstu.edu.cn

Thanks in advance!

**Comment by cfiorelli** [comment]
@CaiJirui-0524 Your key request has been approved. please let us know if you don't receive your key in the next 24 hours

**Comment by CaiJirui-0524** [comment]
The key has been sent to my mailbox, thanks !!
