### ISSUE TITLE
Q: How can I determine my rate limit?

### ISSUE THREAD

**Issue by oyarsa** [allenai/s2-folks#218]
The API (`https://api.semanticscholar.org/graph/v1/paper/search`) gives me 429 errors when I try to make multiple concurrent requests, but as far as I can see, it doesn't tell me how long to wait. How can I know what my true rate limit is so I can respect that instead of retrying the 429s?

**Comment by cfiorelli** [comment]
@oyarsa 
if you can provide the last 6 characters of your api key i can look up your rate limit.

**Comment by oyarsa** [comment]
There you go: `aUM5hc`. Thanks in advance!

**Comment by cfiorelli** [comment]
This key is on our 1RPS plan. That is 1 request per second across all endpoints, cumulative.
