### ISSUE TITLE
Q: dataset release endpoint + fieldsOfStudy

### ISSUE THREAD

**Issue by pedrocr83** [allenai/s2-folks#219]
Any way to restrict/filter the download of releases based on the fieldsOfStudy like it is possible on "Paper bulk search"?

**Comment by cfiorelli** [comment]
@pedrocr83 
Hello,

Thank you for your question! While the Datasets API doesn't natively support filtering by `fieldsOfStudy` during downloads like the `Paper bulk search` API, you can achieve similar functionality by processing the dataset files programmatically.

For example, you can stream and filter records based on `fieldsOfStudy` using a script. Here's a Python snippet demonstrating how to filter dataset files:

https://github.com/allenai/s2-folks/blob/main/examples/Webinar%20Code%20Examples/Datasets_StreamingFiltering.py

This approach allows you to efficiently process and extract only the relevant data without needing to download or process the entire dataset in memory.

Let us know if you need further assistance!

Best regards
