### ISSUE TITLE
Bug: Certain papers have full name information when you click 'cite' on semantic but only initials on website and thru api

### ISSUE THREAD

**Issue by Sekoul** [allenai/s2-folks#222]
**Describe the Bug**
Certain papers have full name information when you click 'cite' on semantic but only initials on website and thru api

**To Reproduce**
Go here: https://www.semanticscholar.org/paper/Vaccine-Hesitancy-Hekel-Dugger/6fcfeea5501639ea4280720eaaf41dfef840e5d7

and compare information aavailable on page versus thru 'cite' button and api

Click on 'cite' and cimpar e
**Expected Behavior**
Full author name available

**Actual Behavior**
only initials avaialable thru API & page

**Screenshots**
If possible, attach screenshots or any visual aids that might clarify the issue.

**Environment Details**
across all platforms and browsers, but on chrome/macbook

**Comment by cfiorelli** [comment]
@Sekoul 
In your example...
When i click cite I see the following authors:
 author={Barbara Emily Hekel and Jennifer Dugger and Bridgette R Pullis and Stanley Cron and Allison P Edwards},

In the webapp on the paper detail page > authors list I see:
B. Hekel, Jennifer Dugger, Bridgette R Pullis, Stanley Cron, Allison P Edwards

In the API i get the following

```
curl -X GET "https://api.semanticscholar.org/graph/v1/paper/CorpusId:265882054?fields=authors" -H "x-api-key: $S2_API_KEY" 
 
{"paperId": "6fcfeea5501639ea4280720eaaf41dfef840e5d7", "authors": [{"authorId": "83118259", "name": "B. Hekel"}, {"authorId": "2256760805", "name": "Jennifer Dugger"}, {"authorId": "11510017", "name": "Bridgette R Pullis"}, {"authorId": "2173727479", "name": "Stanley Cron"}, {"authorId": "2214473128", "name": "Allison P Edwards"}]}

```

These results seem ok, i think? Can you please clarify where you see misalignment?

**Comment by Sekoul** [comment]
Yes, but when you click on 'cite', you see the full name, Barbara.

**Comment by cfiorelli** [comment]
Understood. I'll copy this to our internal work backlog as possible work for 2025. Closing this for now as  we can't currently commit to a fix timeline. 

Best
