### ISSUE TITLE
Fields should be part of the request payload in paper/batch, but documentation says otherwise

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#23]
Originally reported by @codeviking in https://github.com/allenai/scholar/issues/35457

The docs suggests that the fields parameter should be submitted as a query string argument. This doesn't work. Or rather, the payload in this scenario doesn't include the desired fields.

In practice the fields parameter should also be a part of the request payload. This works as expected.

In other words, this didn't work:

curl -d '{ "ids": ["...", "..."] }' https://api.semanticscholar.org/graph/v1/paper/batch?fields=...,...
But this did:

curl -d '{ "ids": ["...", "..."], "fields": ["...", "..." }' https://api.semanticscholar.org/graph/v1/paper/batch
This makes sense, intuitively, which is why I was able to figure it out.

**Comment by cfiorelli** [comment]
relevant issues appear closed
