### ISSUE TITLE
How does the S2 Recommendation API work under the hood?

### ISSUE THREAD

**Issue by Siddharth-Gandhi** [allenai/s2-folks#26]
Hey guys I am building a basic paper recommendation system for my bachelor's thesis and I was wondering if there is there any public information on how the S2 recommendation API works under the hood or if that can be shared? Like any details on the architecture? Is it another neural network or KNN? Any information will be of great help! Please let me know!

I am also curious if any of the code for the recommendations is available from the original SPECTER paper? Specifically section 3.4 here: https://arxiv.org/pdf/2004.07180.pdf.

**Comment by cfiorelli** [comment]
@Siddharth-Gandhi 
Thank you for your inquiry - considering the context of your question and the time since posted I wanted to check to understand if this is still relevant to resolve? 
Thank you!

**Comment by Siddharth-Gandhi** [comment]
Hi @cfiorelli, while I do not need it now, I would still appreciate if you can give a brief explainer of how it works (or link me to something relevant) to just expand my knowledge (as I'm learning about IR and recommender systems now). So if you have a couple minutes of spare time, please do let me know! Much appreciated! Thanks!

**Comment by cfiorelli** [comment]
@Siddharth-Gandhi Quick check in case the ask has developed since last - planning to gather information 

Just in case here's the link to github specter info https://github.com/allenai/specter
