### ISSUE TITLE
10k limit for citation details of a paper

### ISSUE THREAD

**Issue by mehmetemreakbulut** [allenai/s2-folks#27]
Hi everyone, I have been built a social network analysis tool on articles and authors for the graduation project. We have an option for users that they can retrieve the citations of a paper and create a graph with them. However S2AG can not give all the citations of a paper if citationCount is more than 10k when we use 'Details about a paper's citations'  endpoint. Limit is 10k for this endpoint. Is there any workaround for this issue?

**Comment by wammar** [comment]
There's currently no work around for this technical limitation, but we'll consider addressing this limitation in the future.

**Comment by cfiorelli** [comment]
no fix
