### ISSUE TITLE
Where to find PDF URL that appears in the web UI but not in the API?

### ISSUE THREAD

**Issue by justinpchang** [allenai/s2-folks#28]
The publication with `paperId=65b190b353c15a6670fc98614c2a1542286bbb2e` (linked [here](https://www.semanticscholar.org/paper/OPTIMASI-PENCARIAN-DATA-MENGGUNAKAN-TEXT-FILTERING-Algoritma-Winkler/65b190b353c15a6670fc98614c2a1542286bbb2e)) has a link in the web UI to download a PDF. However, when I lookup the paper by id using the Graph API, it is listed as NOT open access with no `openAccessPdf` link. What field is the PDF link in the front-end drawn from?

**Comment by wammar** [comment]
TODO: redefine this as a roadmap feature.

**Comment by cfiorelli** [comment]
@justinpchang To be sure are you seeking to understand if the field on web for paper link is something which is meant to overlap with the relevant api field?

thank you!

**Comment by rrichmond** [comment]
I'm wondering exactly the same thing. The only PDF download link that I can find in paper details from the API is in the field openAccessPdf.url. That said, the website front end often has a PDF links available to other sources. Is there any way to access the alternative PDF links via the API?

**Comment by cfiorelli** [comment]
These are often due to constraints in our agreements with our publishing partners.
