### ISSUE TITLE
What are 504 errors in the S2AG API and how to address them?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#3]
From Andrew White on [slack](https://semanticschol-xyj3882.slack.com/archives/C03055G0WSE/p1678252272221329)

**Comment by robe-ai2** [comment]
@wammar see rodney's commentary in this ticket from last week: https://github.com/allenai/scholar/issues/35719

**Comment by wammar** [comment]
**From our engineering team with a bit of paraphrasing:**

The most likely explanation for getting a 504 is simply that the back-end query is timing out.

If this is intermittent, it's probably load on elasticsearch. We're working on a solution to address the root cause of elasticsearch instability. Stay tuned for updates to that effect on our [release notes](https://github.com/allenai/s2-folks/blob/main/API_RELEASE_NOTES.md).

The timeout may also be deterministic, i.e. always happening for some requests. The /paper, /paper/search, and /author endpoints are most likely to time out when fetching citations/references, because they're potentially fetching N^2 data. If that is happening, the best solution is to switch to the /paper/citations or /paper/references endpoints, where the limit query parameter can be adjusted to reduce the amount of data returned per request.
