### ISSUE TITLE
How to download the datasets?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#33]
> I am interested in looking at the datasets you have available, but when I go to this link https://api.semanticscholar.org/api-docs/datasets#tag/Release-Data there is not really any helpful information on how to actually obtain the dataset. I was wondering what steps were necessary now that I have an api key to download the datasets and potentially use them.

From [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/55474)

**Comment by wammar** [comment]
Our team is working on a few python examples to demonstrate how the REST APIs can be used. It's work in progress, but you can take a sneak peak at https://github.com/allenai/s2-folks/pull/24 which shows how to use the API to interact with the datasets.

**Comment by wammar** [comment]
We just revised the documentation [here](https://api.semanticscholar.org/api-docs/datasets) so that it's easier to download the dataset, along with a python code snippet. Please re-open this ticket if you're still having trouble following the improved documentation.

**Comment by ericchagnon15** [comment]
I was able to download and unzip the files, but when I try to read them with the following usage 
```python
import json
 import os
 import pandas as pd  
files = os.listdir("papers")
   docs = [json.loads(l) for l in open("papers/{}".format(files[1]),"r").readlines()]

```

i get a UnicodeDecodeError

File "C:\Users\username\anaconda3\envs\semantic_scholar\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2483: character maps to <undefined>

**Comment by cfiorelli** [comment]
@ericchagnon15 This looks specifying encoding will help - are you still stuck on this?
