### ISSUE TITLE
TLDR - getting a 500 error on API for some records

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#34]
> if I try the API on https://api.semanticscholar.org/graph/v1/paper/10.1128/mSystems.00606-19/?fields=tldr,year,citationCount then it will throw a 500 error until I remove the tldr field. I only get this on very few papers in a list of about 1500 - any idea why?

From [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/55568)

**Comment by AmberRose2** [comment]
I believe this bug was solved already, and was due to papers that had no abstract, now if that's the case the api will return a "null" in place of the text. 
For example if you click the link above that the user provided you'll see the fix.
