### ISSUE TITLE
Feature request: Search authors by external ID and affiliation

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#36]
> The author search API is very limited, by name only. It would be good to be able to look up authors by DBLP external ID, and by affiliation. It makes less sense that I have to search by name, then check the ID fields on the resutsl.

From [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/55608)

**Comment by cfiorelli** [comment]
closing- seems resolved as of apr 27
