### ISSUE TITLE
Internal server error when using /paper/batch with specific paper IDs

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#38]
> When using the 'get multiple papers' endpoint of the S2AG API, any reuquest that includes the ids ea74a98158624ebc2fc03f7aba2b9056737dc9ae or 317cebe9aef0cc1f0ee36707c06ba38e978ac6bd results in an Internal Server Error. Accessing either paper via the single paper endpoint works with no problems. Some other ids are also affected, though most work perfectly well.
> Feedback was from https://www.semanticscholar.org/paper/Developing-machine-learning-methods-for-automatic-Wang-Zhang/ea74a98158624ebc2fc03f7aba2b9056737dc9ae

From [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/55641)

**Comment by romilly** [comment]
I've attached a file listing over 200 similar problem ids in the hope that this will help to identify the root cause.
[problems.txt](https://github.com/allenai/s2-folks/files/11121912/problems.txt)

**Comment by AmberRose2** [comment]
I've located the problem but am not sure what's causing it/how to fix it.
In the batch endpoint we pass all Id's given by the user through ```lookup_paper_ids``` in ```common.py``` to validate and standardize all id's into corpus Id's.

I added some logging statements so I could see what's happening in the function and you can see we never step into the elif statement that should trigger when someone passes in a sha id.

![Screen Shot 2023-04-07 at 11 17 42 AM](https://user-images.githubusercontent.com/96264681/230658409-26ff8fc9-0a37-4031-ad7a-ca01d23bceec.png)
![Screen Shot 2023-04-07 at 11 21 27 AM](https://user-images.githubusercontent.com/96264681/230658517-25606754-c2e1-414d-ae0b-ccb43923dc95.png)

**Comment by AmberRose2** [comment]
But when I used [regex101.com](https://regex101.com/) to double check the sha it is a match so not sure why the code doesn't seem to think so?
<img width="1403" alt="Screen Shot 2023-04-07 at 11 22 51 AM" src="https://user-images.githubusercontent.com/96264681/230658744-a429b1e0-9164-42de-94d9-3cb20a8664f6.png">

**Comment by romilly** [comment]
The regex looks correct and works correctly in Python code. I don't think I have access to the relevant repository, but my guess is that the failure occurs earlier in `lookup_paper_ids`.  Perhaps an earlier regex matches the id?
