### ISSUE TITLE
Get full text for a specific paper using the /graph endpoint.

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#41]
> Here I have integrate the paper search feature and need to show the paper information in the detail page. But not finding any resource to show full content. Please advice. Thanks

From [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/56089)

**Comment by wammar** [comment]
Note: This was highlighted in the [March'23 user survey (only accessible to AI2 employees)](https://docs.google.com/document/d/1oiBkHn7jZHamudV6LaqLYrGU1crXRqVcdNhO6WrU9VE/edit#)

**Comment by cfiorelli** [comment]
Seems stale - survey work is ongoing/in progress. Closing this to allow for the feature req to self surface in upcoming effort
