### ISSUE TITLE
When using web search and API search, I noticed that I get different search results.

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#42]
> When I search for the paper 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding', I get different results on these two pages: https://www.semanticscholar.org/search?q=BERT%3A%20Pre-training%20of%20Deep%20Bidirectional%20Transformers%20for%20Language%20Understanding&sort=relevance https://api.semanticscholar.org/graph/v1/paper/search?query=BERT:%20Pre-training%20of%20Deep%20Bidirectional%20Transformers%20for%20Language%20Understanding Do you know if there's a reason for this discrepancy? Can I access the API used for web search? Thank you!

From [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/56178).

**Comment by wammar** [comment]
This is by design. We have two separate endpoints in the API to search for authors and papers, while the search functionality on semanticscholar.org allows our users to search for authors and/or papers. 

We're tracking this as a feature request. Please comment on this thread if you are interested in an API endpoint which serves both authors and papers, ideally with a brief explanation of why this is preferable to using the author-specific and paper-specific endpoints already implemented in the API.

**Comment by wammar** [comment]
Relevant: one of our partners, [Andrew White](https://thewhitelab.org/), is building specialized tools for chemistry research using our APIs but the API search results for papers are a lot worse than the results on semanticscholar.org. Adding this note here to boost the priority for this roadmap item.

**Comment by wammar** [comment]
@whitead Thank you for the suggestion and please feel free to add any additional details for the search comparison here.

**Comment by whitead** [comment]
To give a specific example. This search phrase "Meta-learning and peptide design" yields no results on API for search:

[API query](https://api.semanticscholar.org/graph/v1/paper/search?query=Meta-learning+and+peptide+design)

But yields correct results on website

![image](https://github.com/allenai/s2-folks/assets/908389/57fa869d-db25-4c61-bf92-d1498592678b)


Would really like to have the same quality in API as there is on website.

**Comment by whitead** [comment]
Just saw this - wonder if you could do this replacement on server side. Easy to miss! This explains some of my problems, and will get specific examples unrelated to this detail!

![image](https://github.com/allenai/s2-folks/assets/908389/120239bf-e133-4a18-9737-d0372ee9edf4)

**Comment by cfiorelli** [comment]
@whitead Looks like we have a bit of progress on reconciling the web and api results thank you for raising this issue. 
closing here to clean up our pubic side - keeping an eye on it internally.

**Comment by rodneykinney** [comment]
This has been fixed in the api.
