### ISSUE TITLE
How SPECTER embeddings are used in recommendations API?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#5]
> When it comes to the recommendations being returned by the API, I was wondering if you were using the provided specter@v0.1.1 embedding on your end to get a measure of similarity and then return them (maybe you are using a different version of the embeddings). If so, I was wondering what similarity algorithm/formula you were using as I’m noticing that if I run cosine similarity (as well as euclidean distance and simple dot-product) the order of the returned recommendations is random-looking. I am assuming you must be using some other formula though or that maybe the embeddings used are slightly different?

From a private message on slack.

**Comment by jaronjaron** [comment]
They are slightly different. There is a note from the specter repo that addresses this: https://github.com/allenai/specter#public-api

> NOTE: Embeddings that are retrieved from the public APIs will not match the embeddings that can be generated by running the model on this repo. They are produced by two different versions of the SPECTER model. Although embeddings from the two different sets cannot be mixed and matched within the same task, the sets perform similarly on downstream tasks.

**Comment by jdwuarin** [comment]
Hi Jaron, I'm the one who asked the question to Waleed. Thanks for addressing it here.

So, does that mean that internally, the recommendations are being run against embeddings that are generated using the model version from the repo you linked?

**Comment by wammar** [comment]
todo(waleed): follow up with chris/doug to find out about which similarity metric we use for the first stage (knn search), and which model is used for the second stage.

**Comment by de-code** [comment]
I would also be interested in whether the model version is available, that is being used to provide the embedding in the public graph API.

The [paper-embedding-public-apis](https://github.com/allenai/paper-embedding-public-apis) does seem to provide embedding vectors matching those on the a paper returned by the graph API (I found some small differences potentially caused by rounding).

**Comment by cfiorelli** [comment]
I think the resource being asked for is available here - https://huggingface.co/allenai/specter2

But I have confirmed there are some additional signals / processing being applied between corpus and recommendations that drive the exact quality of results you see in the recommendations api
