### ISSUE TITLE
Batch Paper API Endpoint Limited to 50 IDs

### ISSUE THREAD

**Issue by aldengolab** [allenai/s2-folks#52]
The [API Documentation](https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/post_graph_get_papers) states that the batch paper endpoint is capable of handling up to 1000 IDs; however, when more than 50 IDs are POSTed, this endpoint errs with an unhelpful 500 error message.

**Comment by jaronjaron** [comment]
This should be fixed now. Some fields were failing at that 50 ID threshold due to some AWS limitations that have been addressed. Please re-open if you continue to have problems.
