### ISSUE TITLE
Separate Author First Name, Last Name, and Initials fields or inform how we can create citation formats

### ISSUE THREAD

**Issue by christian-salem** [allenai/s2-folks#53]
Hey S2 team, our users are asking for the ability to generate citations in our product. We plan to support MLA, APA, Chicago, and BibTex (just like S2 does). However, I notice the author names in the S2 data do not have separate fields for first and last name.

How does the S2 product configure the different citation formats since they range from "first, last" to "last, first" to "last, first initials"? Any recommendation for us to implement something similar?

**Comment by jaronjaron** [comment]
We do have bibtex formatting integrated into the API, in the `citationStyles` field. Is this what you are looking for, in addition to those other formats?

https://api.semanticscholar.org/graph/v1/paper/a4cec122a08216fe8a3bc19b22e78fbaea096256?fields=citationStyles

![Screenshot 2023-04-13 at 3 39 30 PM](https://user-images.githubusercontent.com/1452635/231898231-235d8ce6-127e-4468-97a9-1d2a01af2139.png)

**Comment by wammar** [comment]
The main downside is that the coverage of first/last name is currently low so it may not be a terribly useful addition until we come up with better ways to parse author names into first/last name. 

@christian-salem my recommendation is to either use our out-of-the-box implementation or re-implement it using heuristics to de-construct the full name into first/last (which may only work well for western names).

**Comment by christian-salem** [comment]
Thanks guys. Makes sense.

When you say "We're actively working on an infrastructure project which will make it easier to expose more of our internal fields to public API users", I'm guessing that means the different formats that you surface in the S2 web product (APA, MLA, Chicago) are currently powered by internal fields?

**Comment by jaronjaron** [comment]
All the fields used to generate the citation format should already be available in the API, in [this request](https://api.semanticscholar.org/graph/v1/paper/a4cec122a08216fe8a3bc19b22e78fbaea096256?fields=citationStyles,title,authors,journal,year,publicationTypes) you can see the formatted bibtex as well as all the underlying data.

The main difference between the website and the API is they use different methods to generate the citation format (server side vs client side).

**Comment by wammar** [comment]
> I'm guessing that means the different formats that you surface in the S2 web product (APA, MLA, Chicago) are currently powered by internal fields?

Sorry I missed this question earlier. Yes, this is what I meant.

**Comment by wammar** [comment]
That said, to @jaronjaron 's point, our implementation of the citation generator primarily uses the full name since we don't have first/last name as metadata for most authors (only as heuristics based on the full name).
