### ISSUE TITLE
How do different ways of combining keywords in the query param affect search results?

### ISSUE THREAD

**Issue by eimenhmdt** [allenai/s2-folks#54]
Hey! 

When searching for papers by keywords, does it make a difference how the keywords are listed in the query param? 

For example:

query=keyword,keyword,keyword or
query=keyword+keyword+keyword or
query=keyword keyword keyword

**Comment by cfiorelli** [comment]
@eimenhmdt I've not observed any differences in testing - are you seeing anything suspicious?
