### ISSUE TITLE
fetching a large amount of data for a specific country or date range

### ISSUE THREAD

**Issue by Alaamoheb** [allenai/s2-folks#55]
I wanna to fetch around 20K. I know there is a limit. but is there any way to get it in several time not in a one time?
also considering that I want to collect for a specific country and date like, US or any country for the last ten years for example.
any one help me!

**Comment by wammar** [comment]
I am afraid the only way to do this at the moment is to download the entire dataset (see documentation for the [datasets endpoints](https://api.semanticscholar.org/api-docs/datasets)) and filtering using heuristics.

**Comment by wammar** [comment]
One more thing: If there's a specific keyword you can use to search for papers, then you can filter the results based on a range of years as documented [here](https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/get_graph_get_paper_search).

**Comment by Alaamoheb** [comment]
also, what should I do to fetch around 21000?
