### ISSUE TITLE
Updated API time

### ISSUE THREAD

**Issue by Alaamoheb** [allenai/s2-folks#56]
I notice that there is update in the API endpoint request up to 5,000 requests per 5 minutes.
I have an API Key from one month ago with 100 requests per sec.
but I needed a higher rate . should I request a new API key, or the update is already done on the one I got?

**Comment by wammar** [comment]
The new rate limit (5K/5min) only applies for authenticated user requests. The rate limit for authenticated users (like yourself) is significantly higher.
