### ISSUE TITLE
Batch API is not working for num_ids > 100 

### ISSUE THREAD

**Issue by Siddharth-Gandhi** [allenai/s2-folks#59]
The batch API seems to not be working/working quite poorly. It only responds for a maximum of 100 ids instead of the [proposed 1000 ids](https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/post_graph_get_papers) and it also seems to take way too long to respond. You can see some tests I did in the screenshot below. For size [200,500] it does something but gives back 504 after 30s and for any size in [500,1000], it just immediately gives 500 error.

#52 seems like a similar issue which was closed but it appears it hasn't yet been fixed fully. Even #58 seems similar. So please fix!

![7AA443F9-D072-428F-ACF1-601F8C9173F8](https://user-images.githubusercontent.com/61461606/233836234-a6fb86e5-3bd3-4aab-9d14-7b8e89c247e0.jpg)

**Comment by wammar** [comment]
@Siddharth-Gandhi thank you for reporting this issue Siddharth! I'll be discussing it with the team tomorrow. 

Question: I'm aware of the other issues you pointed to but have you personally seen a similar pattern in the past or is this the first time you experience this problem?

**Comment by Siddharth-Gandhi** [comment]
@wammar I have not used the batch API extensively before, so I am not aware if this was the case previously. However, I have used the references/citations API before and that was also prone to random 504s for no reason (even if I was sending requests at much lesser than the rate limit on my API key).

**Comment by rodneykinney** [comment]
There are some easy fixes here.

We are fetching the [citations](https://github.com/allenai/s2-public-api/blob/main/app/graph_api.py#L290) and [references](https://github.com/allenai/s2-public-api/blob/main/app/graph_api.py#L293) even if they were not requested. Same for the [embeddings](https://github.com/allenai/s2-public-api/blob/main/app/graph_api.py#L305) and [TLDRs](https://github.com/allenai/s2-public-api/blob/main/app/graph_api.py#L306)

My recommendation:
 - Only fetch citations/references/embeddings/TLDRs if they were requested
- Limit batch requests that fetch citations/references/embeddings/TLDRs to <= 100 papers. 
  - Change documentation
  - Return useful error message

**Comment by AmberRose2** [comment]
Addressed this issue, thank you for pointing it out!
