### ISSUE TITLE
Return paper ids based on filters without a search query

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#62]
In context of discussing the common need of API partners to retrieve a large number of papers in a given field, e.g., https://github.com/allenai/s2-folks/issues/12, which is not the intended use of the search endpoint, @aletar89 suggested:

> Maybe a solution would be an API that returns paper ids based on filters without a search query? For example, I want all the computer science papers from 2022 with more than 0 citations and get the paper-ids of all the papers (paginated if needed), then I can run over the list and do further analysis with the paper-details API.

**Comment by cfiorelli** [comment]
I think the datasets endpoint solves this. closing
