### ISSUE TITLE
Is it possible to look up the publisher partner, data provider, or aggregator providing Semantic Scholar with the abstract for a given paper?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#63]
Is it possible to look up the publisher partner, data provider, or aggregator providing Semantic Scholar with the abstract for a given paper?

_Originally posted by @Androbin in https://github.com/allenai/s2-folks/issues/13#issuecomment-1475933304_

**Comment by cfiorelli** [comment]
@Androbin Looks like this question came from you - after so much time I'm tentatively closing but please reply if you're still seeking answers (sorry to just close but balancing old questions against immediate actions a bit over here)

Thank you

**Comment by bingohuang** [comment]
I also encountered the problem, some papers have abstracts on semanticscholar.org but not in the API and datasets.
How did you get the acstract on semanticscholar.org? Is authorization required?
Thank you very much.@cfiorelli
