### ISSUE TITLE
Find datasets used in a given paper

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#65]
https://sagebionetworks.org/portals/ have professionally curated linking of papers to datasets. Can we surface them using the public APIs?

**Comment by wammar** [comment]
Feasibility discussion [on slack](https://allenai.slack.com/archives/C7VDASV33/p1682032531559879) (only accessible to AI2 employees).

**Comment by cfiorelli** [comment]
feasibility review looks like we dont have a path forward here. closing now in lieu of future justification
