### ISSUE TITLE
Is it possible to sort the paper response by citationCount for paper's citations API 

### ISSUE THREAD

**Issue by avijit15** [allenai/s2-folks#66]
Hi guys,

I am working on a project where I need to use a citation network. I am using the paper's citation API and the response, I am getting, is sorted by publication date in descending order. Do we have any options to sort this response by citationCount  field?

**Comment by csaparna** [comment]
I have a question related to this. Is there a filtering option at any paper endpoints using any of the return fields? For example, can I filter by isInfluential=True to get response with all influential references?

**Comment by mansimov** [comment]
+1 on this, would be very useful for [Sourcely](https://www.sourcely.net/)

any expectation on when searching the papers by the minimum number of citationCount would be available in the API?

thanks!

**Comment by cfiorelli** [comment]
Hello everyone. I think for the needs outlined here the functionality in paper bulk search will resolve much of the needs. Please have a look and let us know how this helps!
https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/get_graph_paper_relevance_search
