### ISSUE TITLE
API gallery page for ThinkSpark

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#67]
Next steps:

- [ ] Where is this hosted? @wammar 
- [ ] Test out integration between webflow + [Shaurya's demo](https://6979-130-203-139-14.ngrok.io/).
- [ ] Review minimal design and iterate as needed.
- [ ] Design a thumbnail for [the top-level gallery page](https://semanticscholar.webflow.io/product/api/gallery).
- [ ] Launch.

**Comment by shauryr** [comment]
Putting in the system requirements for the host machine - 

The machine should have access to 1 GPU with atleast 10Gb of VRAM. More is better, allowing us to load bigger models. 
- We need this to run the summarizer and the embedding service. 

Please let me know if this needs any clarification.

**Comment by wammar** [comment]
Question to Shaurya: do you already have IAM login to our AWS services with
some permissions, or do we need to create a new login?

**Comment by shauryr** [comment]
I used to have IAM login. But I dont know if it still works. Even if it works I dont remember the password. Can we create a new login?

**Comment by cfiorelli** [comment]
@mattdeitke @shauryr ,
I'm a little out of the loop on this process for partner pages - still anything to do here lmk/reopen
