### ISSUE TITLE
Q: How should partners acknowledge using the Semantic Scholar APIs

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#68]
> We were asked to include a Semantic Scholar attribute on our site. Could you please let us know if there is a correct procedure, such as displaying the Semantic Scholar logo?

Asked by Keiichiro Takahashi (via [email](https://mail.google.com/mail/u/0/#inbox/FMfcgzGsmDrQQpBWhQBJMSJvXrBCzDfk)).

**Comment by de-code** [comment]
Also interested in the answer with more clarification on it. This is what Joe sent me via email a while ago:

> Please remember Semantic Scholar requires link back to the article paper detail page URL if you are planning to surface any results derived from our datasets as well as attribution on public accessible websites representing your project.
> 
> Additionally, if you plan to publish any results/findings in any format, we would require attribution for our contributions to your outcome.

**Comment by de-code** [comment]
Thank you for sharing https://www.semanticscholar.org/product/api/license via Slack

From the attribution section:

> Licensee will include an attribution to “Semantic Scholar” on its website or in any published materials for contributions from S2 through Licensee’s use of the API and/or S2 Data.

That could be in the "about" page of the website or similar?

i.e. there is no requirement to attribute on each page the API was used?

Do you have suggested wording?

The attribution in the license also stats:

> If Licensee uses the SEMANTIC SCHOLAR trademark and logo (“S2 Marks”) on any public displays of S2 Data, all such use will be in accordance with AI2’s branding requirements.

Do you have a link to the branding requirements?

**Comment by Jgordo72** [comment]
Hi Daniel, here you can find the is the branding tool kit link its near the bottom of the page: https://www.semanticscholar.org/about

This has all our approved logos to use on your site/tool.

Can you let me know your quesitons around the attribution and link back question from the previous comment?

**Comment by de-code** [comment]
> Can you let me know your questions around the attribution and link back question from the previous comment?

Thank you. I wasn't sure whether there are expectations where the link to Semantic Scholar should be placed.
e.g. this could be on the "About" page of a website?

**Comment by cfiorelli** [comment]
@de-code ,
Our terms dont specify on placement - As long as the stated requirements of the terms are met I don't think we have any other concerns. Let us know if you're still holding on this?

**Comment by de-code** [comment]
Just adding that on [Slack, connectedpapers was seen as a good example](https://semanticschol-xyj3882.slack.com/archives/C03027UT6R3/p1697338156129749?thread_ts=1697325159.006979&cid=C03027UT6R3).
