### ISSUE TITLE
Paper Search API: Add support for `sort` parameter to allow sorting by publication date (descending)

### ISSUE THREAD

**Issue by de-code** [allenai/s2-folks#70]
**Is your feature request related to a problem? Please describe.**
As a researcher, I would like to keep up to date with the literature and search for recent preprint publications matching my search.

**Describe the solution you'd like**
The Semantic Scholar website allows sorting by `Recency` (represented as the query parameter `sort=pub-date`).
It would be great to have that sort option to be available via the API.

**Describe alternatives you've considered**
Specifying the `year` parameter can restrict the search a bit but still isn't quite the same.
Sorting could also happen client side, but would require to retrieve all of the search results.

**Additional context**

**Comment by wammar** [comment]
@rodneykinney fyi

**Comment by wammar** [comment]
@de-code I have a question related to this request. Today, our /citations/ endpoint returns most recent papers first, e.g.,

**API call:** https://api.semanticscholar.org/graph/v1/paper/649def34f8be52c8b66281af98ae884c09aef38b/citations?fields=publicationDate,intents

**API response:** 
```
{
  "offset": 0,
  "next": 100,
  "data": [
    {
      "intents": [
        
      ],
      "citingPaper": {
        "paperId": "116145af7e956b23d0d9a81fdad8cb4f9a166531",
        "publicationDate": "2023-06-01"
      }
    },
    {
      "intents": [
        "background"
      ],
      "citingPaper": {
        "paperId": "5d46d0589df44234dc50b7425138048c8789aef4",
        "publicationDate": "2023-04-28"
      }
    },
    {
      "intents": [
        
      ],
      "citingPaper": {
        "paperId": "cbdf6e77aa6cfd650a49e8f0ae95726c1e97540a",
        "publicationDate": "2023-04-23"
      }
    },
    {
      "intents": [
        
      ],
      "citingPaper": {
        "paperId": "4a1cd12aeda0356ed4a1c30533313a8b68f9a55b",
        "publicationDate": "2023-04-15"
      }
    },
    {
      "intents": [
        "methodology"
      ],
      "citingPaper": {
        "paperId": "1ad9a295ea841599383e5ae3e88381438d4a7db3",
        "publicationDate": "2023-03-30"
      }
    },
...
```

We need to do some optimizations to speed up the response time for this endpoint, but we may sacrifice our ability to return a sorted list. In your experience, how bad would this be?

FYI @yoganandc

**Comment by de-code** [comment]
Thank you for your quick response and looking into it.

> We need to do some optimizations to speed up the response time for this endpoint, but we may sacrifice our ability to return a sorted list. In your experience, how bad would this be?

I don't have much opinion on it as we don't use citations or currently have plans to. When we did look at citations in the past, we were interested in all of the citations. In that case the sorting could easily be done in the client, especially when you provide the information like the publication date.
I don't know what use cases would benefit from a server side sorted citation list.

Just hypothesising:

- Check whether there are more recent citations since having called the API last time:
  - A potential even better alternative would then be a filter parameter
- Only show most recent citations on a website:
  - Most papers do not have that many citations. Loading all of the citations may not be ideal but should not be such a big issue.

**Comment by AtomScott** [comment]
+1 on this. It would be great to have a `sort=pub-date` parameter or even a option to narrow down search results to a specific date so searching publications from last week, or in the past few days would become possible.

**Comment by cfiorelli** [comment]
I suspect controls in our newly released Paper Bulk Search will resolve this ask!
https://api.semanticscholar.org/api-docs/#tag/Paper-Data/operation/get_graph_paper_bulk_search
