### ISSUE TITLE
Venue not matching a number of Research Square DOIs

### ISSUE THREAD

**Issue by de-code** [allenai/s2-folks#71]
**Describe the bug**

Where the DOI starts with `10.21203/rs`, the venue should be `Research Square`.
But that isn't always the case.

For example for `10.21203/rs.3.rs-1270359/v1` the API returns the venue `PLoS ONE`.

```json
{"paperId": "c8d6bd6263003aed85d25c029832b181acf02ddc", "externalIds": {"DOI": "10.21203/rs.3.rs-1270359/v1", "CorpusId": 258179155, "PubMed": "37068083"}, "title": "The impact of government actions and risk perception on the promotion of self-protective behaviors during the COVID-19 pandemic.", "venue": "PLoS ONE"}
```

The Semantic Scholar web UI shows the same information for the venue, but links the PDF to research square.

The DOI does resolve to Research Square.

There is also a paper on `Plos ONE` with the same title, but with the DOI `10.1371/journal.pone.0284433`.

For another example `10.21203/rs.3.rs-2660358/v1` there isn't any venue.

Searching on for the venue `Research Square` seems to only yield in 366 results. Whereas there should be many many more.

**To Reproduce**

Pick any Research Square DOI and search for it via the API or web UI.

**Expected behavior**
The venue should always be `Research Square`.

**Screenshots**

![image](https://user-images.githubusercontent.com/1016473/235937501-b0140191-56bd-4765-8592-82dab6ec0c8a.png)

![image](https://user-images.githubusercontent.com/1016473/235937689-91f19ff3-d1ff-4f99-8875-75a72626033f.png)

![image](https://user-images.githubusercontent.com/1016473/235937804-b9be38e0-31b8-4435-a7d3-caed9340bbff.png)

![image](https://user-images.githubusercontent.com/1016473/235937382-c9c4a852-e4dd-4794-b51f-7d8f0d8172b3.png)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by wammar** [comment]
@de-code Venue normalization is hard. Let me reach out to people who know more about this than I do.

@power10dan @rodneykinney  FYI

**Comment by de-code** [comment]
Just to provide more details.

### Some data

The API response for the Research Square DOI `10.21203/rs.3.rs-1270359/v1`,
`https://api.semanticscholar.org/graph/v1/paper/DOI:10.21203/rs.3.rs-1270359/v1?fields=externalIds,venue,publicationVenue,publicationTypes,publicationDate`

```json
{
  "paperId": "c8d6bd6263003aed85d25c029832b181acf02ddc",
  "externalIds": {
    "DOI": "10.21203/rs.3.rs-1270359/v1",
    "CorpusId": 258179155,
    "PubMed": "37068083"
  },
  "publicationVenue": {
    "id": "0aed7a40-85f3-4c66-9e1b-c1556c57001b",
    "name": "PLoS ONE",
    "type": "journal",
    "alternate_names": [
      "Plo ONE",
      "PLOS ONE",
      "PLO ONE"
    ],
    "issn": "1932-6203",
    "url": "https://journals.plos.org/plosone/",
    "alternate_urls": [
      "http://www.plosone.org/"
    ]
  },
  "venue": "PLoS ONE",
  "publicationTypes": [
    "JournalArticle",
    "Review"
  ],
  "publicationDate": "2023-04-17"
}
```

For some reasons I am getting a 404 for `10.1371/journal.pone.0284433`.

Searching for the title only brings back the paper with the Research Square DOI (same with the exact title used for PloS ONE).

`https://api.semanticscholar.org/graph/v1/paper/search?fields=externalIds,venue,publicationVenue,publicationTypes,publicationDate&limit=10&offset=0&query=The%20Impact%20of%20Government%20Actions%20and%20Risk%20Perception%20on%20the%20Promotion%20of%20Self-Protective%20Behaviors%20During%20the%20COVID-19%20Pandemic`

```json
{
  "total": 1,
  "offset": 0,
  "data": [
    {
      "paperId": "c8d6bd6263003aed85d25c029832b181acf02ddc",
      "externalIds": {
        "DOI": "10.21203/rs.3.rs-1270359/v1",
        "CorpusId": 258179155,
        "PubMed": "37068083"
      },
      "publicationVenue": {
        "id": "0aed7a40-85f3-4c66-9e1b-c1556c57001b",
        "name": "PLoS ONE",
        "type": "journal",
        "alternate_names": [
          "Plo ONE",
          "PLOS ONE",
          "PLO ONE"
        ],
        "issn": "1932-6203",
        "url": "https://journals.plos.org/plosone/",
        "alternate_urls": [
          "http://www.plosone.org/"
        ]
      },
      "venue": "PLoS ONE",
      "publicationTypes": [
        "JournalArticle",
        "Review"
      ],
      "publicationDate": "2023-04-17"
    }
  ]
}
```

[10.21203/rs.3.rs-1270359/v1](https://doi.org/10.21203/rs.3.rs-1270359/v1) was posted `16 Mar, 2022`.
[10.1371/journal.pone.0284433](https://doi.org/10.1371/journal.pone.0284433) was published `April 17, 2023`.

The pubmed id `37068083` points to an article with the PLoS ONE DOI `10.1371/journal.pone.0284433`.

## Observations and Comments

### `venue`, `publicationVenue`, `publicationDate` (and `publicationTypes`) seem to be consistent

While that is good in a way, the consequence is that the publicationDate also can't be reliably used 

### The API would make more sense, if the DOI was pointing to the PLoS ONE DOI instead of Research Square.

If the same API response was pointing to  `10.1371/journal.pone.0284433` instead of `10.21203/rs.3.rs-1270359/v1`, it would make more sense. (Of course when querying for the PLoS ONE DOI instead).

In fact, linking the information to `10.21203/rs.3.rs-1270359/v1` seems to be a bug.

It would mean that Semantic Scholar no longer has information about the preprint.
Which seem to be the case, as all of the fields relate to the PLoS ONE article?

(Of course there could be potential issues if the same internal paperId was used)

### Keeping information of preprint as a separate version

It would be great to keep the information about the preprint.

For example EuropePMC has information for both DOIs and links them.

For `https://www.ebi.ac.uk/europepmc/webservices/rest/search?format=json&resulttype=core&query=DOI:10.21203/rs.3.rs-1270359/v1`, the field `commentCorrectionList` contains that link (perhaps not pretty or intuitive but functional).

That could perhaps be an idea.

Alternatively the history could be maintained within the same record. But that doesn't seem practical, as there may be many fields (if not all), that we would like to keep a history of.

This might affect the search, depending on the use case, it may or may not be desirable to return both versions. EuropePMC for examples only includes the latest Research Square version (but does include preprint and journal article).

**Comment by de-code** [comment]
An example of a preprint (not Research Square), that isn't in Semantic Scholar:

`10.1101/2023.01.13.523998`

But the journal publication is:

`10.3389/fimmu.2023.1144224`

**Comment by cfiorelli** [comment]
@de-code - As im working through the backlog/prioritization could you confirm you're still seeing issues on this one?

**Comment by de-code** [comment]
Hi @cfiorelli I checked and the example in https://github.com/allenai/s2-folks/issues/71#issuecomment-1548241694 cannot be found by that anymore (and then it's not the bug described here but the "feature" that preprints published elsewhere are no longer treated a preprint).

I looked at some recent examples where there is a mismatch and found a few:

- `10.21203/rs.3.rs-3269310/v1` showsn `bioRxiv`
- `10.21203/rs.3.rs-3111925/v1` showsn `Endocrine`
- `10.21203/rs.3.rs-1246803/v1` doesn't have venue

Overall, out of the 321 Research Square preprints we've ingested since 1st October, there are 140 examples where the venue isn't `Research Square`.
(There may be a small chance that some have corrected since then, I only double checked the examples above)

**Comment by cfiorelli** [comment]
Logging this for Data team / pipeline maintenance team review. thanks for the detailed updates!
