### ISSUE TITLE
Paper Search API: Ability to search by preprint server

### ISSUE THREAD

**Issue by de-code** [allenai/s2-folks#75]
**Is your feature request related to a problem? Please describe.**
As a researcher, I would like to keep up to date with the literature and search for recent **preprint** publications matching my search.

**Describe the solution you'd like**
It would be good to filter the results to only include preprints. Ideally even the option to include specific preprint servers.

**Describe alternatives you've considered**
The `venue` filter seems initially like a good option. But it doesn't currently seem to match the preprint server for a number of papers (see #71) and may actually have a different purpose.
Another workaround is to filter the search results client side. But the vast majority of search results do not seem to be preprints. Leading to multiple search pagination requests that could otherwise be just one.

**Additional context**
In EuropePMC, one can filter the results by adding `(SRC:PPR)` for all of the indexed preprint servers. Or select individual preprint server by adding for example `(PUBLISHER:"bioRxiv" OR PUBLISHER:"medRxiv" OR PUBLISHER:"Research Square")`

Related to #71 #70

**Comment by de-code** [comment]
Perhaps having a filter for the DOI prefix could be one option.

**Comment by wammar** [comment]
> The venue filter seems initially like a good option. But it doesn't currently seem to match the preprint server for a number of papers (see https://github.com/allenai/s2-folks/issues/71) and may actually have a different purpose.

@power10dan @rodneykinney Any comments on whether we're planning to have the `venue` field reflect whether we have a preprint server as one of the sources for a given paper? I suspect this requires allowing multiple values since some canonical papers are first prepublished then published at an official venue.

**Comment by wammar** [comment]
> Another workaround is to filter the search results client side. But the vast majority of search results do not seem to be preprints. Leading to multiple search pagination requests that could otherwise be just one.

@de-code I'm not sure I understand why this solution is not sufficient. I hear you that pagination is annoying but also kind of unavoidable given the constraints of the HTTP protocol, so you'd probably need to implement pagination even if we add the requested filter.

**Comment by rodneykinney** [comment]
> @power10dan @rodneykinney Any comments on whether we're planning to have the `venue` field reflect whether we have a preprint server as one of the sources for a given paper?

We have ArXiv, bioRxiv, medRxiv, and Research Square in our database of normalized venues, so the `venue` facet should identify papers that we get from those sources. If a paper is subsequently published in a peer-review venue, we will drop the association with the preprint server, but I think that's okay for this purpose.

The core issue is https://github.com/allenai/s2-folks/issues/71. We don't use DOI prefix to identify the venue because we don't have a comprehensive mapping from DOI prefix to ISSN, but we would probably expand our coverage significantly if we could construct one.

**Comment by de-code** [comment]
> > Another workaround is to filter the search results client side. But the vast majority of search results do not seem to be preprints. Leading to multiple search pagination requests that could otherwise be just one.
> 
> @de-code I'm not sure I understand why this solution is not sufficient. I hear you that pagination is annoying but also kind of unavoidable given the constraints of the HTTP protocol, so you'd probably need to implement pagination even if we add the requested filter.

It is not using pagination in general. But having to go through many pages to find the papers matching certain criteria.

As an example, let's say I want to search for "covid" for bioRxiv/medRix (DOI prefix `10.1101`), for the year `2023.

* First page: https://api.semanticscholar.org/graph/v1/paper/search?fields=externalIds&limit=100&offset=0&year=2023&query=covid
  * None of them
* Second page (offset=100)
  * None of them
* Third page (offset=200)
  * Two items

That means I had to retrieve 300 results to find 2 papers matching my criteria.

> > Perhaps having a filter for the DOI prefix could be one option.
> 
> @de-code To clarify: do you mean filtering the search results to only include papers which has a DOI prefix?

Yes, say I could pass in a DOI prefix, or preferably a list of prefixes then the majority of the filtering could happen server side.
There may still be the odd ones that are not captured that way. e.g. papers with the DOI prefix `10.1101` that belong to a journal. Or SciELO and SciELO Preprints share the same DOI prefix.

In a way that would be a proxy for the venue of the preprint though.

> We have ArXiv, bioRxiv, medRxiv, and Research Square in our database of normalized venues,

Do you have a list of those normalized venues?

> so the `venue` facet should identify papers that we get from those sources. If a paper is subsequently published in a peer-review venue, we will drop the association with the preprint server

In your view, the venue in the list should accurately reflect the preprint until the paper is published in a journal?

> , but I think that's okay for this purpose.

Is that because by the time it is published it will no longer be recent, and therefore no longer be relevant for the use case?

(In the PLoS ONE example it was published after a month, not sure what the minimum number of days to publication is)

**Comment by rodneykinney** [comment]
> Do you have a list of those normalized venues?

Our list of normalized venues is available as the `publication-venues` dataset. https://api.semanticscholar.org/datasets/v1/release/latest

> Is that because by the time it is published it will no longer be recent, and therefore no longer be relevant for the use case?

I meant that once it's published, it's no longer a preprint, and this use case is primarily about finding preprints.

**Comment by de-code** [comment]
> I meant that once it's published, it's no longer a preprint, and this use case is primarily about finding preprints.

It seems that we at eLife / Sciety, but also preprint servers like bioRxiv have a different opinion on that.
We believe a preprint stays being a preprint.
[eLife for example has moved away from an accept/reject decision](https://elifesciences.org/inside-elife/54d63486/elife-s-new-model-changing-the-way-you-share-your-research).
In the "Publish-Review-Curate" world that we are striving towards, the publication is the preprint itself. (Although eLife will also produce a "Reviewed Preprint")

--

I've also separated #92 regarding evaluated preprints. That would be even more affected by removing the preprint from the dataset.

**Comment by cfiorelli** [comment]
Moving to triage for data team & consider exposing DOI search via PBS/PS

**Comment by smitar** [comment]
@jaronjaron moving this issue to the integrity team project board

**Comment by cfiorelli** [comment]
For the moment the resource outlined below copied from above is the maximum commitment or solution we have available 

```

> > Do you have a list of those normalized venues?
> 
> Our list of normalized venues is available as the publication-venues dataset. https://api.semanticscholar.org/datasets/v1/release/latest
> 
> Is that because by the time it is published it will no longer be recent, and therefore no longer be relevant for the use case?
> 
> I meant that once it's published, it's no longer a preprint, and this use case is primarily about finding preprints.

```
