### ISSUE TITLE
Q: I want to download the PDF files using Semantic Scholar API KEY. How can I do it?

### ISSUE THREAD

**Issue by kevinleerongordon** [allenai/s2-folks#76]
Hello, Honestly, I am first at Semantic Scholar API KEY.
Please let me know how I can download the PDF files using this API key.

Thanks,
Kevin

**Comment by cfiorelli** [comment]
@kevinleerongordon Please have a look at our Webinar examples directory https://github.com/allenai/s2-folks/tree/main/examples

This video may also be useful 
https://www.youtube.com/watch?v=_BQwU2i_nh4
