### ISSUE TITLE
Publication date vs. arxiv submission date

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#8]
> I'm looking into the publication dates of papers and I see that for papers that were submitted to ArXiv, the publication date is the same as the ArXiv submission date for 90% of Semantic Scholar papers. Is this because:
> i) these papers were submitted to ArXiv before they were published in the journal, or
> ii) the publication dates for these papers were not known so the ArXiv dates were used as publication dates?
> I see that the [official documentation](https://www.semanticscholar.org/faq#publication-dates) says that the publication date is either the print date or the journal publication date as provided by the source, but details are not listed. It would be great if someone could provide some insight into how these dates are collected.
> More generally, our research would greatly profit from having the actual journal publication dates for papers that have ArXiv submission dates as their publication dates. Is there a way to get them? We (me and 
> [@Przemyslaw Grabowicz](https://semanticschol-xyj3882.slack.com/team/U04QY3Q2BL1) ) study at UMass Amherst the effects of early promotion and revisions of scientific publications on the number of citations.

From [slack](https://semanticschol-xyj3882.slack.com/archives/C03055G0WSE/p1677081202700579)

**Comment by wammar** [comment]
The answer is nuanced. One of the critical steps in our pipeline is to create a cluster of papers which are so close to each other they are probably different versions of the same paper, followed by "business logic" which determines which paper should be used to populate the metadata in our knowledge graph (e.g., prefer "real" publication to presubmissions). Both (i) and (ii) are possible explanations. I realize this doesn't help you with your research. I don't know of a way to get the publication date when the API currently returns the arxiv submission dates.

**Comment by wammar** [comment]
Documenting a follow up question on slack: 

<img width="844" alt="image" src="https://user-images.githubusercontent.com/1858803/226059793-fc69b615-fe8d-45a6-86db-984a6ada0688.png">

**Comment by chhandak1** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/21310252/226358854-a37d1a40-4ed4-4a31-81b5-75cecfa1419d.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/21310252/226358865-1f910121-ce5f-45c9-a1b0-73c0dafb77b6.png)
I have done the cross-referencing for the publication dates from the S2 API and ArXiv. These 2 images show the difference between the ArXiv submission date and the SS (Semantic Scholar) publication date (both of them are the same histograms, the second one is zoomed in). There are no papers where the difference is less than 0, i.e., no papers that have a Semantic Scholar publication date that is after the  ArXiv submission date. Now, the Semantic Scholar publication date can either be the "true" journal publication date or an ArXiv (or any other e-print) submission date. Based on this, can we make the assumption that the Semantic Scholar publication date is the earlier date between the true journal publication date and the ArXiv submission date? 

Also, the papers that have ArXiv submission date on Semantic Scholar may include papers for which we don't know what was the true publication date. Can we separate them from the ones for which we know the true date, but the true date was after the ArXiv submission date? Any data regarding this would be really helpful.

**Comment by przemyslslaw** [comment]
Thanks for the pointer to your prior work @wammar -- great study, well ahead of its time, congrats! We're doing a similar analysis (using arXiv and WikiCFP as well) with doubly robust estimators and more control variables and more treatments. We would also like to use more data than just computer science conferences -- that's why we're looking into the publication dates.

**Comment by wammar** [comment]
> Based on this, can we make the assumption that the Semantic Scholar publication date is the earlier date between the true journal publication date and the ArXiv submission date? 

Looking into this.

**Comment by chhandak1** [comment]
Hello @wammar, just checking if there are any updates on this.

**Comment by cfiorelli** [comment]
@chhandak1 
Sorry for the delay on this - Christopher here working to support Semantic Scholar's API...
Can you share with me whether any characteristics of the observations or your inquiry have changed since the last comments from march?

**Comment by chhandak1** [comment]
Hello Christopher, thanks for looking into this! We have currently restricted the scope of our study to only computer science conferences. We want to increase the scope to other fields of study as well and getting an answer to this previous question would help us do that. Our question remains the same as the one we asked in March.

> ![MicrosoftTeams-image](https://user-images.githubusercontent.com/21310252/226358854-a37d1a40-4ed4-4a31-81b5-75cecfa1419d.png) ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/21310252/226358865-1f910121-ce5f-45c9-a1b0-73c0dafb77b6.png) I have done the cross-referencing for the publication dates from the S2 API and ArXiv. These 2 images show the difference between the ArXiv submission date and the SS (Semantic Scholar) publication date (both of them are the same histograms, the second one is zoomed in). There are no papers where the difference is less than 0, i.e., no papers that have a Semantic Scholar publication date that is after the  ArXiv submission date. Now, the Semantic Scholar publication date can either be the "true" journal publication date or an ArXiv (or any other e-print) submission date. Based on this, can we make the assumption that the Semantic Scholar publication date is the earlier date between the true journal publication date and the ArXiv submission date? 
> 
> Also, the papers that have ArXiv submission date on Semantic Scholar may include papers for which we don't know what was the true publication date. Can we separate them from the ones for which we know the true date, but the true date was after the ArXiv submission date? Any data regarding this would be really helpful.

**Comment by cfiorelli** [comment]
The answer is basically "its really complicated". we have a lot of date logic written that works for some cases but not for others because publishers are not consistent. if standardizing arxiv specifically needs to happen then theoretically we could do this but it would represent - as we currently understand the task - a rather massive undertaking. More work to understand the scale of work required and potential value this effort would provide to our community to help us prioritize.

In the moment I would unofficially label this as a low priority medium impact data integrity type of issue - please comment as appropriate, i'm certain other contributors here might have more insight and experience in this case than myself.

Thank you !
