### ISSUE TITLE
Different values for "total" field and the number of papers available from the response

### ISSUE THREAD

**Issue by csaparna** [allenai/s2-folks#80]
**Describe the bug**
Hi, I was pulling papers for a query  at paper endpoint To get all papers, I repeated the query by changing the offset till it reaches the total that is returned in the query. Even though total = 422, the json returned next =346, with offset=300 and limit=100. Also, when I queried with offset=400, I got an error. To check what is happening, I did the same query on the SS webpage. As you see in the attached screenshot, total is 422. But on page 34, it returns only 6 results. I f I click into page 35, it returns an error. Is this behavior expected?

**To Reproduce**
1. My search terms was 'LOXL2' on the website and I filtered for the last 5 years
2. My API query URLs were of the format:
'https://api.semanticscholar.org/graph/v1/paper/search?query=LOXL2&year=2018-2023&fields=paperId,externalIds,title,year,authors,journal,referenceCount,citationCount,tldr,abstract,publicationTypes&offset=0&limit=100'

with offset changing till offset<total

**Expected behavior**
I expected the search results to have 422 papers. I also expected the query with offset=400 to work

**Screenshots**
![image](https://github.com/allenai/s2-folks/assets/67968246/40432ee3-8a6c-4525-ac4a-81f32bc39e18)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Comment by wammar** [comment]
Thanks for asking this @csaparna . This is a known limitation of elastic search and therefore is the expected behavior. 

One caveat: the search implementation on the semanticscholar.org website is different from the implementation in the API endpoints.

**Comment by csaparna** [comment]
Thanks @wammar ! Any recommended method to deal with this limitation? Is the 'next' field a better criteria to avoid running into the error?
