### ISSUE TITLE
2023-05-03 release lacks the "papers" dataset

### ISSUE THREAD

**Issue by aletar89** [allenai/s2-folks#81]
**Describe the bug**
The recently release bulk API download lacks some of the datasets compared to previous releases

**To Reproduce**
Visit https://api.semanticscholar.org/datasets/v1/release/2023-05-03 and compare it to https://api.semanticscholar.org/datasets/v1/release/2023-04-18

**Expected behavior**
The previous bulks had the following datasets:

['abstracts',  'authors',  'citations',  'embeddings',  'paper-ids',   'papers',  'publication-venues',  's2orc', 'tldrs']

While the new one only has:
['embeddings', 'paper-ids', 'publication-venues', 's2orc', 'tldrs']

**Additional context**
Is there a schedule to the releases? Sometimes it's weekly, sometimes more rare. 
It would be nice to know in advance when the next dataset will be released and whether there is a delay expected or format changes.

**Comment by wammar** [comment]
Thanks for reporting this @aletar89 . I'm looking into it, but it's unlikely to be resolved during the weekend.

**Comment by aletar89** [comment]
2023-05-09 seems to be have the missing datasets

**Comment by wammar** [comment]
This issue was also reported by [Michael Dorrill](https://semanticscholar.freshdesk.com/a/contacts/17054429187) on [freshdesk](https://semanticscholar.freshdesk.com/a/tickets/56822).

> To whom it may concern, I hope this message finds you well. My name is Michael Dorrill, and I am a researcher at the Institute for Humane Studies. I wanted to bring to your attention an issue that we have encountered with the latest release of your bulk dataset. We have been utilizing your dataset for a significant portion of our research, and have found that several critical datasets that were included in previous releases (including the 4/18 release) are missing from the latest version. These datasets include abstracts, authors, citations, embeddings, and papers. I was hoping to inquire about the status of these datasets and whether we can expect to see them return in future iterations of the bulk release. Any information you can provide would be greatly appreciated. Thank you for your time and assistance.

**Comment by wammar** [comment]
Note to eng team: I think the main work needed here is to diagnose why this happens occasionally.

**Comment by rodneykinney** [comment]
Removed the `2023-05-03` release from the API, to avoid future confusion:

```
$ curl "https://api.semanticscholar.org/datasets/v1/release/2023-05-03/"
{"error":"No release with ID 2023-05-03"}
```

**Comment by wammar** [comment]
This would also be easy to monitor when we have [data metrics](https://docs.google.com/document/d/1TSJ86PYRPL0_fQt_M3utUsoxbuLqg9Z1b7HXku450tI/edit#bookmark=id.4gg3ficwdl3a) as part of the next milestone for the API health page.

**Comment by wammar** [comment]
@rodneykinney Thank you for removing the incomplete release (2023-05-03). Any thoughts on why we missed `['abstracts', 'authors', 'citations', 'papers']`, and how likely it is for this issue to happen in future releases? It seems like this was the first problematic release in the past ~4 months or so, although the the 2023-01-03 release does look fine now.

**Comment by rodneykinney** [comment]
I don't see any errors in the [logs](https://s2build.inf.ai2.in:8543/viewLog.html?buildId=2443959&buildTypeId=SemanticScholar_SparkCluster_PipelineIncremental_BuildS2agDataset&tab=buildLog&_focus=229#_state=199) for that date. Would need to open an investigation to know what went wrong.

This is the first time we've made a release with incomplete datasets, to my knowledge. We should have better monitoring do detect if it happens again https://github.com/allenai/scholar/issues/35206
