### ISSUE TITLE
Getting Figures & Tables from Semantic Scholar APIs

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#83]
**Is your feature request related to a problem? Please describe.**
I am trying to develop an application using the Semantic Scholar API which uses Figures and Tables from scientific papers.

**Describe the solution you'd like**
I saw that on each Semantic Scholar page there is a field which contains dropdowns with information about that paper?especially, with a dropdown of "Figures and Tables" along with their corresponding captions. I am wondering if the semantic scholar graph API can return this information? It doesn't appear to be on the docs. 

**Describe alternatives you've considered**
No alternative provided by user.

**Additional context**
Created by @wammar on behalf of Houjun Liu houjun@stanford.edu ([Freshdesk ticket](https://semanticscholar.freshdesk.com/a/tickets/56495))

**Comment by wammar** [comment]
> I am wondering if the semantic scholar graph API can return this information? 
Thank you for the question Houjun! Our APIs don't provide this information, but we're considering adding it sometime in 2023. Feel free to subscribe to this issue in order to be notified when we make progress on this.

**Comment by cfiorelli** [comment]
I've not used this but one of our team members saw your message and thought this might be helpful!
https://github.com/allenai/deepfigures-open
