### ISSUE TITLE
API error "too many requests" despite staying below the limit

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#84]
**Describe the bug**
Even if my application stays below the 5000 requests per 5 minutes that are available for testing I receive the error message "too many requests" from time to time. 

**To Reproduce**
Information was not provided by user in Freshdesk.

**Expected behavior**
HTTP response 200

**Additional context**

- I'm using the /paper/search endpoint.
- Created by @wammar on behalf of [Adrian Zimmermann](https://semanticscholar.freshdesk.com/a/contacts/17054267482) based on [this freshdesk ticket](https://semanticscholar.freshdesk.com/a/tickets/56611)

**Comment by wammar** [comment]
I'm afraid this is a known problem with our implementation of the rate limiting. Until we address this, we recommend adding a bit of logic to catch this response rate and adjust the rate at which you're submitting calls accordingly, e.g., every time you get this error, multiple the sleep time between API calls by x 1.1.

**Comment by wammar** [comment]
Another complaint by [Josh Cara](https://semanticscholar.freshdesk.com/a/contacts/17054268529) (via a [freshdesk ticket](https://semanticscholar.freshdesk.com/a/tickets/56614))

> Hi, I am using s2ag api search by keyword, and it keeps giving me "too many request" response while l didn't even close to the 5000 times per 5 minutes limit. As I tested, other ways are fine, only by searching by keywords can cause this problem. Please tell me how to fix it. Thank you.

**Comment by yvonne-chou** [comment]
The 5000 request per 5 minute limit is for API calls without an API key, and is a shared pool for all unauthenticated users. If you are running into this issue, you can request an API key [here](https://www.semanticscholar.org/product/api#api-key-form).

**Comment by itsrun** [comment]
> The 5000 request per 5 minute limit is for API calls without an API key, and is a shared pool for all unauthenticated users. If you are running into this issue, you can request an API key [here](https://www.semanticscholar.org/product/api#api-key-form).

May I ask what's the rate limit for authenticated users? I'm using an API key but still have to limit to 2 requests per second to avoid 429 errors...
