### ISSUE TITLE
Q: What are the terms and conditions for using the Semantic Scholar APIs?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#86]
> .. I am a developer. I wanted to ask you about the price and conditions to use your API for a mobile application that I am going to develop?

Created on behalf of [Seymen Sipahi](https://semanticscholar.freshdesk.com/a/contacts/17054409881) (see [freshdesk ticket](https://semanticscholar.freshdesk.com/a/tickets/56804))

**Comment by yvonne-chou** [comment]
The Semantic Scholar API License Agreement can be found here.
https://www.semanticscholar.org/product/api/license
