### ISSUE TITLE
Q: For every new release do you provide all the data from before that release?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#87]
> For every new release do you provide all the data from before that release? Or do you only provide the delta between all releases and the new release?

Created based on a [freshdesk ticket](https://semanticscholar.freshdesk.com/a/tickets/56810) on behalf of [igal](https://semanticscholar.freshdesk.com/a/contacts/17054413205).

**Comment by wammar** [comment]
We provide the entire corpus in each release, but we're also planning to release incremental updates. Subscribe to this ticket in order to get notifications about incremental dataset releases.

**Comment by wammar** [comment]
Note: Another partner (Xu Cui) just expressed interest in this on slack [here](https://semanticschol-xyj3882.slack.com/archives/C03027UT6R3/p1684342627047199)

**Comment by cfiorelli** [comment]
action needs here seem resolved
