### ISSUE TITLE
Q: data distribution in the files of data dump

### ISSUE THREAD

**Issue by puzzz21** [allenai/s2-folks#90]
Hello, I am downloading the s2orc data dump from https://api.semanticscholar.org/datasets/v1/release/2023-03-28/dataset/s2orc. The dataset has been divided into multiple files. I was wondering which criteria or condition has been used to divide the datasets into the multiple files, for example, is it ordered based on the year, journal, fields or venues. I am currently planning to using only one file, but I wanted to know if this file would contain the distributed data from various fields, journals etc. or just from partially distributed fields or journals.

**Comment by cfiorelli** [comment]
@puzzz21 I believe these are split by size constraint and batched into papers/corpus ID.
let me know if you need anything else!

**Comment by puzzz21** [comment]
@cfiorelli  Thank you for your response.
