### ISSUE TITLE
Paper Search API: Ability to search by "evaluated" preprint server

### ISSUE THREAD

**Issue by de-code** [allenai/s2-folks#92]
**Is your feature request related to a problem? Please describe.**
This is an extension of #75

As a researcher, I would like to keep up to date with the literature and search for recent preprint publications matching my search, that have been **evaluated**.

**Describe the solution you'd like**
Some way of getting the status of being evaluated into Semantic Scholar and use it as a search filter query.

**Describe alternatives you've considered**
Filter client side, which requires more pagination through search (and discarding results that have not been evaluated).

**Additional context**
Sciety is aggregating evaluations from various evaluation groups.
We have a way of getting the status of being evaluated, into Europe PMC (the current implementation might change).
We are then able to use that in a query, in our case by adding ` (LABS_PUBS:"2112")` to the search query.

I believe Europe PMC are also getting other reviews not via Sciety.

Evaluation or review doesn't necessarily, and often doesn't mean a separate journal publication.
Evaluation also doesn't necessarily mean endorsed. It is just a public assessment, as a review or sometimes just some feedback.

**Comment by cfiorelli** [comment]
Closing in conjujnction with end state of issue #75
