### ISSUE TITLE
Search API: "Requested data for this limit and/or offset is not available" before total is reached

### ISSUE THREAD

**Issue by de-code** [allenai/s2-folks#96]
**Describe the bug**
When searching, the API responds with a total.
That total can at least in this example not be fully retrieved.
I can only retrieve `992` out of `1735` items.

**To Reproduce**

Last successful request:

```console
$ curl 'https://api.semanticscholar.org/graph/v1/paper/search?year=2023&venue=bioRxiv%2CmedRxiv%2CResearch+Square&query=covid&fields=externalIds%2Curl%2Ctitle%2Cabstract%2Cauthors&offset=900&limit=100' | jq '{total, offset, next}'
{
  "total": 1735,
  "offset": 900,
  "next": 992
}
```

Failing request:

```console
$ curl 'https://api.semanticscholar.org/graph/v1/paper/search?year=2023&venue=bioRxiv%2CmedRxiv%2CResearch+Square&query=covid&fields=externalIds%2Curl%2Ctitle%2Cabstract%2Cauthors&offset=992&limit=100' | jq
{
  "error": "Requested data for this limit and/or offset is not available"
}
```

This seem to suggest that there are no more items:

```console
$ curl 'https://api.semanticscholar.org/graph/v1/paper/search?year=2023&venue=bioRxiv%2CmedRxiv%2CResearch+Square&query=covid&fields=externalIds%2Curl%2Ctitle%2Cabstract%2Cauthors&offset=991&limit=100' | jq '{total, offset, next}'
{
  "total": 1735,
  "offset": 991,
  "next": 992
}
```

**Expected behavior**
As the total indicates `1735` items (below the maximum offset of `9999`), I  would expect to be able to retrieve all of the items.
The next pointer on the previous page points to `992` (expected `1000`).
But that page can't be retrieved.

**Comment by rodneykinney** [comment]
Our search service was returning different values for `total` depending on whether the offset was above or below 1000. Fixed now.
