### ISSUE TITLE
Wrong list of authors

### ISSUE THREAD

**Issue by csaparna** [allenai/s2-folks#97]
**Describe the bug**
I queried for the list of authors for a paper with its paper id at the author endpoint. The actual author list shown at the publication website had 17 authors. However, the API query returned 100 authors. The 100 authors included the 17 authors as the first 17 elements, followed by many others and also duplicates.

**To Reproduce**
```
url = f'http://api.semanticscholar.org/graph/v1/paper/4014954d25a9f385e06ef386c5534c3392d9c599/authors'
print(url)
headers = {key: secret}
response = requests.get(url, headers=headers)
if response.status_code != 200:
    raise ValueError("There was an error in the api request!")
else:
    result = response.json()
len(result['data']
```
returns 100
**Expected behavior**

len(result['data'] should return 17 and data should only have 17 elements with author id and name 

**Additional context**
I don't know if this is a widespread issue. A list of 100 authors was unusual, prompting me to dig in. I would be happy to help with finding the root cause.

**Comment by stupendousC** [comment]
[Slack discussion for context/reference](https://allenai.slack.com/archives/C05DDH64FHR/p1687383931243249).

**Comment by cfiorelli** [comment]
This seems to be resolved except our result is showing (on my end) 16 not 17 as originally reported - @csaparna please let us know if youre still not getting what you would expect to see here (considering some time has gone by)
